### ISSUE TITLE
Meeting Type "Women" bug

### ISSUE THREAD

**Issue by OSAwebsite** [code4recovery/12-step-meeting-list#101]
One of my meetings in version 3.6.4 has "Women" as the type. In the regular meeting list this appears in the groupname: "groupname / Women" and in bold. In the meeting details green it show bold and green. I think this might be a leftover that was missed when we were moving to this latest version. It is not super serious, but it would be better if this feature was removed.

You can see it in action here:
http://al-anon.alateen.on.ca/meetings/?tsml-day=any&tsml-type=W

Thanks for all the hard work - I know changing functionality in a live solution is not easy and there are bound to be bugs. But all in all I feel you are all doing a great job!

Nicky

**Comment by tech2serve** [comment]
Thank you for writing this up here. I'll try to look at it this week.

**Comment by tech2serve** [comment]
@OSAwebsite--

Things are not as clear as I thought. Investigating your site I see the issue you're describing. However, I am not seeing that behavior on my site.

What custom styling do you have loading?

**Comment by OSAwebsite** [comment]
OK, here is what I checked. I have the latest version of Wordpress/Plugin on a staging site. that site has no custom css at all. Although the word "women' is less prominently present there, it still comes up in the group name. And it still shows as bold green in the details. 

Check it out here:
http://www.iamnow.today/meetings/?tsml-day=any&tsml-query=women

All the meetings I have on the live site are present on the staging site and 'women' is the only one that shows up this way.

I have no specific plugins there and nothing that acts on the 12 step plugin.

Does this help?

**Comment by tech2serve** [comment]
Getting to stripped and basic site definitely helps. 

For the purpose of providing some background, we refer to these as flags. Flags are shown both in the meeting list and on the single meeting page. In addition to the  "Women" flag, we have  "Men", "Temporary Closure" (TC) and "Online Meeting" (ONL). We don't simultaneous display TC and ONL; if both types are checked for a meeting, ONL will cause "Online meeting" to be displayed as a flag while TC is skipped. Either the `men` or `women` types will display as flags if appropriate regardless of when the meeting is temporarily closed, online, or both. Similarly, if the meeting is temporarily closed, the flags will be shown in the color red, while if the meeting is online, the flags will be colored green. If only the "Men" or the "Women" flag is displayed, the color should be basically the same as the meeting name albeit smaller in text. But, one of the other two flags is germane, the color and styling of all the flags will match that.

Back to your situation. The reason the "Women" flag is showing in green on your single meeting page is because the meeting  also has they ONL type. What is curious to me is that single meeting page nor the meeting list are not showing the "Online Meeting" flag. It appears that is the bug given you haven't made any modifications to the plugin through your theme. I suspect the bug is related to the program type setting. Please confirm what program you have set here for each site:
I've tested my website using Safari (13.1), Firefox (74.0.1) and Chrome (80.0.3987.163 ) and the behavior is as we designed.

**Comment by OSAwebsite** [comment]
Interesting information.
So I decided to try a couple of things. Took out both the online flag and the women flag. Nothing is shown now in the name. Then added 'Women'. It showed up in the name of the group, but no longer in green. Added Online flag: nothing changed. I noticed that there is no info in the URL field: this is one of those meetings people have to call a telephone number for to get the specifics. So I then added  fake zoom link into the URL field and lo and behold, the 'women' flag is back in bold and green.

There must be some assumed hierarchy in what is shown and in what way - I my database a meeting is either open, closed or online. No other options. So I will never have TC and ONL at the same time. If the meeting is open, none of those is ticked. I would say that it should work the same in your code. But... I have not seen the online flag in any of my online meetings.

It is not a big deal for me at this time, because I add (elec) to all group names for my own purposes so it is quite clear which meetings are online. But with previous versions leading up to the current pluginversion, I did have the red online flag a couple of times. But have not seen it at all recently.

In your code, do you expect the tick box value to be in the order you display them on the website? Because I replicated the values in my underlying database but in an order that makes sense to me.

Which means it could result in:

Online
Women

or 

Women
Online

**Comment by tech2serve** [comment]
I found the bug. We didn't add `ONL` and `TC` as types that will generate flags for Al-Anon programs. I will fix that and then the flags will show as expected. That should come out in the next release. We had talked about it, but I didn't get the change made. 

As far as order of the flags, I am not confident enough in how Wordpress' database routines work to tell you any given order will be maintained.

**Comment by OSAwebsite** [comment]
That's great! For me the order is not really important one way or the other. It's just when I enter the values they are easy to miss if the order is random. But I can adjust when this becomes necessary. Thanks for Sherlock Holmesing this!

**Comment by tech2serve** [comment]
Ahhh. You're talking about the order on the admin page where you enter or edit a meeting? Yes, those should always be in alphabetical (if we get it right in creating the array in `variables.php` order on that page. However, I can't say for certain what order they will display in on the front end.

**Comment by OSAwebsite** [comment]
Actually... I was referring to how the data come in. Depending on when which value is entered, my list of types is not typically alphabetical. So if your code where to go from value 1, to 2, etc and expect Online to always come before Women, then that is not the case in the csv. But, it does not seem to matter for what you are describing. Will update on the staging site first to see if we have found the cure.... Thanks!

**Comment by tech2serve** [comment]
@OSAwebsite,

You were absolute right about my not getting this bug fully fixed. My apologies. I've make the changes and will put out a bug fix soon..
