### ISSUE TITLE
Increase "upcoming" timelimit

### ISSUE THREAD

**Issue by alex-m-dc** [code4recovery/12-step-meeting-list#107]
Hello,
My idea is: When "upcoming" time is selected in list to display meetings which start at the top of the hour for up to 10 minutes (+/-) into the hour. Let people join meetings in progress.

Thanks!

**Comment by tech2serve** [comment]
Please confirm you're talking about for the widget.

**Comment by joshreisner** [comment]
FWIW, the Meeting Guide app scrolls you to the next meeting from now - 5 minutes

**Comment by crispyatl** [comment]
Looks like the relevant code is in filter_time() in filter_meetings.php, specifically:
```
            } elseif ($time == 'upcoming') {
                return (strcmp($this->now, $meeting['time']) <= 0);
            }

```

$this->now is in H:i (2-digit hour and 2-digit minute or HH:MM) format, so basically it will only match if the meeting time is >= the current time to the exact minute.

We could add a config option for a threshold in minutes to show meetings (say **tsml_upcoming_meeting_threshold**), use `date_diff()` instead of `strcmp()` to find the time difference in minutes, then check that against the threshold. The default threshold should probably be 0 which is backwards compatible with the current implementation.

Alternatively, you could just check if $meeting['end_time'] has passed or not.

Or you could combine the two.  tsml_upcoming_meeting_threshold=0 could be the current behavior, -1 could be "use meeting end_time", and anything greater than 0 can be the threshold in minutes.

Thoughts?

Since I'm pretty new to the code here, I'm not sure what the proper place to override the value is, but I'd guess functions.php is the best place.

**Comment by joshreisner** [comment]
I think the quickest way to do this is to update this line of that file: https://github.com/code4recovery/12-step-meeting-list/blob/master/includes/filter_meetings.php#L79

```
$this->now = current_time('H:i');
```

I think you just want to subtract 10 minutes from now basically

**Comment by joshreisner** [comment]
Complete with release of `3.12`
