### ISSUE TITLE
Contact information of group meeting is not displayed

### ISSUE THREAD

**Issue by joerggebauer** [code4recovery/12-step-meeting-list#108]
**Describe the bug**
When a meeting is part of a group the information entered in the contact section (name, email, phone) is not displayed (rendered) in the frontend

**To Reproduce**
1. Create a meeting
2. Make it part of a group
3. Enter contact details
4. Check frontend

**Expected behavior**
The contacts information is displayed in the frontend.

**Comment by joshreisner** [comment]
Hi @joerggebauer contact info is not displayed by default. You can change this by going to Meetings > Import & Settings and changing the "Meeting / Group contacts" setting on the right.

**Comment by joerggebauer** [comment]
Hi @joshreisner ,

this doesn't help, unfortunately. Please see this post where the bug has already been confirmed: https://wordpress.org/support/topic/contact-information-only-visible-for-logged-in-users/

Thanks!

**Comment by tech2serve** [comment]
Hi @joerggebauer & @joshreisner --

My apologies as I didn't get over here and acknowledge the issue report. This is a validated bug report and something I'll try to look at later this week.

**Comment by joshreisner** [comment]
Oh ok my bad

**Comment by RECLO-CER** [comment]
Hi Josh, we are just wondering if you could provide an update on this issue as the local contact information for meetings has stopped displaying on our site and now members and newcomers are no longer able to get in touch with the listed meetings. This is important especially during lock down as members need to confirm if the meeting is running and/or the online link and passwords need to be given out etc. Many thanks for all your service! Matt RECLO, CER

**Comment by tech2serve** [comment]
Hi Matt--

I'm working on this but am a bit unsure on how the behavior *should* be. In particular, if someone has three meetings as part of a group, and one meeting has different contact information, should that override the group contact information? What if some of the fields are blank for a group contact, should the meeting contact information merger or override? Should a meeting contact automatically become the group contact if a meeting is selected to be part of a group? 

Those are the kinds of questions we're trying to answer before we start changing code.

As someone clearly trying to use the feature, I'd be happy to hear your thoughts?

**Comment by RECLO-CER** [comment]
Hello!

Thanks so much for the reply.

 

I think ideally we would have the option to have separate entries for the “group”, and then entries for the “meeting”. 

 

For example the fields could be Group Name, Group Email, Group mailing address etc. and this information would be “private” Then you would have separately the Meeting Contact Name, Email, Phone, which would be “public”. The group fields would be optional, but the meeting details would be compulsory. Perhaps you could have for the meeting contacts a “same as group” contacts option.

 

What is most important is that when a user selects a meeting from our meeting list then they can always see the meeting contacts name, email and/or phone so they can get in touch with a local member for that particular meeting, even if that individual meeting is part of a larger multi-meeting group.

 

Note: we currently advise all users that “before attending a meeting, we recommend checking the latest meeting information with the local meeting contact” and this practice is especially important now as meeting arrangements are always changing due to COVID-19 lockdown requirements. 

 

I hope this helps and please let me know if I can support further.

 

Many thanks for all your service,

Matt

**Comment by joshreisner** [comment]
Sounds like we might be adding a second request about having both group and individual meeting contact info on the same meeting. Leaving that aside for a second, I can't reproduce the original behavior described.

I created a test website, entered test contact information, made it as part of a group, and made sure I was logged out when viewing the frontend.

<img width="1027" alt="Screen Shot 2020-06-27 at 7 10 10 AM" src="https://user-images.githubusercontent.com/1551689/85924211-91683000-b845-11ea-8d3e-232fed631287.png">

I can see the contact info, right? Am I missing a step?

**Comment by tech2serve** [comment]
Add contact information to a meeting first, then convert it to a group and add/change contact information. 

I'll try to duplicate again with screen caps.

**Comment by joshreisner** [comment]
@tech2serve no need, I observed this behavior as well when working on 7th tradition options. this wasn't clear from the OP though
