### ISSUE TITLE
Prevent translation of addresses by Google Translate

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#1092]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/1090

<div type='discussions-op-text'>

<sup>Originally posted by **VickiB11** March 15, 2023</sup>
Our website recently added Google Translate so that the Spanish speaking groups can see the TSML meeting finder in Spanish.  However, the meeting location, address, and region are incorrectly translated.  Is there a way to tag the meeting finder not to translate when using Google Translate?

Vicki B
Georgia Al-Anon

![Meetings using Google Translate](https://user-images.githubusercontent.com/74988606/225457591-ec194049-1774-4afc-b0fd-626a5718f7ca.png)
</div>

places to address (sorry) the issue:
* table view
* table view after ajax filter
* map view
* detail page left side
* detail page right side

you can add `class="notranslate"` to the parent tag of the address, or wrap it in a span

**Comment by troybon** [comment]
Hey Josh, 

Do you have any timeline on a chance to put this enhancement into the system? 

Thanks,
Troy

**Comment by joshreisner** [comment]
@troybon to be honest, i dont think anyone is working on this right now, so no eta to share at this time.

i'm fully allocated to other projects for the time being. if anyone were to volunteer i don't think it would be a heavy lift

**Comment by SIA-WEBSUP** [comment]
@troybon , can you check if this be accomplished by applying the 'notranslate' CSS class to the widget?
Here's a couple of links that might be of interest:
   - https://www.3schools.in/2022/07/disable-google-translate-notranslate.html
   - https://ncoughlin.com/posts/disable-google-translate-specific-page-paragraph/

**Comment by gkovats** [comment]
@joshreisner FYI I put a PR in for this here:
https://github.com/code4recovery/tsml-ui/pull/348

Don't know the relationship between the two, assuming it has to merge in tsml-ui before the dist JS updates in this plugin. Let me know if I'm missing steps.

**Comment by gkovats** [comment]
Just looking, if we're preventing translation of street address, likely should do these as well:

- Location / Group: sometimes a repeat of the street address
- Region: should likely follow address, since it also uses proper geographic names

![image](https://github.com/code4recovery/12-step-meeting-list/assets/1187583/3eb8897a-c8e3-4547-8148-2839425eaad8)

The others, probably safe to attempt translation. It's hard to tell with all groups / meeting names, and fuzzy nature of auto translate. 

This make sense, do Location / Group, Address, and Region? It looks like a very small change, just clarifying exact change.

**Comment by joshreisner** [comment]
yes that sounds consistent with the original request

> However, the meeting location, address, and region are incorrectly translated. Is there a way to tag the meeting finder not to translate when using Google Translate?

**Comment by joshreisner** [comment]
this issue should be fixed now by #1290 - thanks @gkovats !!
