### ISSUE TITLE
[Bug]:  OIAA Meeting Guide is down

### ISSUE THREAD

**Issue by melindafries** [code4recovery/12-step-meeting-list#1293]
### Contact Details

web.services@aa-intergroup.org

### Website With Issue

https://aa-intergroup.org/meetings/

### What happened?

OIAA Meeting Guide is down. It is displaying this error:
SyntaxError: Unexpected non-whitespace character after JSON at position 6673480 (line 1 column 6673481)

### What browsers are you seeing the problem on?

Chrome

**Comment by joshreisner** [comment]
goood morning @melindafries - thanks for posting here. any idea what time this started?

**Comment by melindafries** [comment]
good morning @joshreisner  - we got the first email about it at 7:49am CT this morning.

**Comment by joshreisner** [comment]
ok looks like it's fixed now - all i did is i went in and edted one meeting :) i saved a copy of the list through so i'll see if i cant figure out what went wrong

**Comment by melindafries** [comment]
Thanks so much. Let me know if theirs anything else we need to do on our end. I'll mark this as closed.

**Comment by joshreisner** [comment]
best i can tell the JSON got messed up - seems strange that this has only happened one time so far with Central in about a year! i don't think this is due to any code or database changes since there haven't been any recently.

here's a copy of the JSON that was throwing an error:
[6436f5a3f03fdecef8459055-2.json](https://github.com/code4recovery/12-step-meeting-list/files/13794873/6436f5a3f03fdecef8459055-2.json)

seems like it had a complete set of proper JSON, and then, appended to that, two partial fragments of addtional JSON:

in this screenshot i've highlighted the first extra fragment. above that is valid JSON, below that is the second fragment

<img width="1446" alt="Screenshot 2023-12-29 at 8 25 16 AM" src="https://github.com/code4recovery/12-step-meeting-list/assets/1551689/e35ddee3-5365-4443-b70f-1ed97ca76779">

**Comment by joshreisner** [comment]
if this happens again with the invalid JSON message (one thing i'm pleased about is how accurate the error message was!), i advise making a change to any listing. in this case i removed an exclamation point from the recently-edited great escape group notes: https://central.aa-intergroup.org/groups/658d9653f936e644e31fd12f?index - i don't think the edit itself was a factor so much as letting central make another attempt at re-saving the file properly

i'm going to move this to the central repository - in the future please issues there: https://github.com/code4recovery/central/issues (but again i appreciate you adding the issue to github!!!!)
