### ISSUE TITLE
Meetings are blank

### ISSUE THREAD

**Issue by scottvanwa2** [code4recovery/12-step-meeting-list#134]
**Describe the bug**
Moved this over from the WP site (https://wordpress.org/support/topic/meetings-are-blank/#post-13170261)

I am updating dozens of meetings who are moving back to being in person. While I was at it I upgraded the plug-in version. When I click on any meeting on any day there is no content. I am unsure why. 

**To Reproduce**
1. Go to https://www.vancouveraa.org/meetings/?tsml-day=0
2. Click on any meeting link
5. See that page is blank

**Expected behavior**
Page should show meeting info

**Screenshots**
![image](https://user-images.githubusercontent.com/66804755/88468181-95af5980-ce94-11ea-91d7-a2d9f7b71500.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Tried both Firefox and Chrome current versions

**Comment by tech2serve** [comment]
Hi @scottvanwa2,

Thanks for moving the discussion over here.

I just tried looking at your meeting list and I'm now getting this:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/31904316/88468432-c72e2200-cea0-11ea-9843-59215ce50a8e.png">

This is almost always due to an issue with permalinks. Have you tried going into the permalinks page and re-saving the settings?

**Comment by scottvanwa2** [comment]
I just resaved the permalinks and now the pages are completely blank again.

**Comment by scottvanwa2** [comment]
I also just disabled all plugins, saved permalinks, reactivated plugins. I also removed the Masks Required form the Location field. The meeting page is still coming up blank.

**Comment by tech2serve** [comment]
Just to confirm, have you changed the permalink settings from "Plain" to a different structure?

I'm really at kind of a loss. This is not something I've seen before, and since nobody else has reported it with the latest version, I guess the next idea I can come up with is to back up your meetings database, delete the plug, reinstall it, and import your database. Kind of a nuclear option, but unless one of the other devs jumps in with a suggestion....

**Comment by scottvanwa2** [comment]
I didn't change any settings on the permalinks. Just clicked Save button leaving everything as is. Here is how it looks
![image](https://user-images.githubusercontent.com/66804755/88468737-b2e82600-ce9c-11ea-826d-54f8d4feeabf.png)

**Comment by tech2serve** [comment]
Do you have an option with your hosting account to clear cache?

**Comment by tech2serve** [comment]
@scottvanwa2, Another member on our team suspects the issue might be a PHP error.

Assuming you have access, please enable `WP_DEBUG` in `wp-config.php` and see if you get error on your screen.

Thanks.

**Comment by scottvanwa2** [comment]
Hi all, I was able to figure out the issue. We were on PHP version 5.4. I upgraded to 5.6 and then upgraded WP to the latest version and the meetings started showing up again. An old case of "ain't no one updated the server in a loooong time". Thanks for your help and patience!

**Comment by tech2serve** [comment]
Thank you for letting us know. Yeah, hoping more service providers will get to PHP 7 :-)
