### ISSUE TITLE
Create Meeting Type for In-Person Meetings

### ISSUE THREAD

**Issue by Harriet-Vane** [code4recovery/12-step-meeting-list#153]
For people who are looking for an in-person meeting, there isn't an easy way for them to sort the list and just see meetings that are happening on-site. I'd love it if I could just check a "Type" when I'm listing the meetings that are in-person, so these folks can easily find what they need.

In contrast, I easily can tag online meetings (by adding the link for the videoconference) so the words "Online Meeting" show up in list view, but I can't see a way to add a tag that indicates a meeting is happening in person in a similar way. 

I'd love to be able to choose a meeting "Type" to indicate a meeting was happening in-person. And having an in-person Type that I could multi-select would also solve for the growing number of meetings that want to indicate they're meeting onsite AND over zoom at the same time. I've been hearing that more and more meetings are planning to reopen (when they eventually reopen) with this kind of simulcast, in-person/zoom setup, so I'd love to get ahead of that need if I can.

If there's a way to do this that I haven't considered, please let me know! Definitely open to the ol' user error possibility. :)

PS I'm only choosing the "location closed" Type when a meeting is _completely_ on hiatus for now, not meeting in any format for the foreseeable future, since I don't want any meetings that are actually happening to get greyed out/struckthrough in list view (and I think the zoom link gets erased when I choose "location closed" anyway).

Thank you!

**Comment by tech2serve** [comment]
In the plugin (and the Meeting Guide app) if a meeting isn't tagged with "Location Temporarily Closed", it is meeting in-person. Some groups are choosing to leave meetings active and adding the online meeting as a indicator that the groups is also using an online option.

I don't envision us adding another tag for "in-person" meetings (since that is the default), but groups are welcome to add their own custom types (see FAQ) although those will not show up in the Meeting Guide app.

**Comment by eae** [comment]
Hi there, I opened #158 because I did not see this as an open suggestion.  I would respectfully request that this issue stay open for a while in the hopes of attracting more eyeballs and opinions.

Several thoughts.

The request here and on #158 is to add the ability to filter for just the meetings that are happening in person.  For our website, that request is coming from users of our site.  We are currently fulfilling it by periodically updating a PDF document where we manually maintain a list; this is less than convenient for all for many reasons.  The fact that our website awkwardly provides some data that's not available in the Meeting Guide app detracts from the usefulness of the Meeting Guide app and discourages our intergroup office's volunteers from recommending the app.

Maybe it is the intention of the app and plugin developers that in-person meetings are "default", but that does not help people see a list of just those meetings (excluding meetings that are JUST happening online or not happening at all).  There is no concept of "default" in the UI, nor is there the concept of some types being mutually exclusive.  Without the ability to see a list of meetings that are just the "default", there is no standard way to provide this information to our users.

I cannot speak for other plugin users, but in our area not all groups are equally diligent about updating the intergroup about changes to their meeting.  As a result, we have several broad categories: a) meetings we know are happening online only; b) meetings we know are happening in person only; c) meetings we know are not happening at all; d) meetings we know are happening in person and "simulcasting" to Zoom; e) meetings that have split into one meeting that is just face-to-face and one meeting that is just on Zoom, effectively becoming one type a and one type b; and f) meetings about which we have not received an update.  

Finally, there already is an "outdoor meeting" type.  As the fall and winter seasons approach in the Northern hemisphere, I wonder what is the need being met by being able to filter outdoor meetings by type (even though their outdoorness is often represented in their location) while there is no ability to filter indoor meetings by type.

**Comment by tech2serve** [comment]
> The request here and on #158 is to add the ability to filter for just the meetings that are happening in person.

I find the idea of improving filtering -- to be able to exclude certain types of meetings -- is valid, and I ask that you write up an issue (New Feature Request) along these lines. 

Many of us feel there are already too many types covered, and frankly we're confusing meeting types with meeting statuses with... you get the idea. So many meeting types makes it difficult for users to correctly enter or select them consistently.

For the historical perspective, I'll add that until recently we did not plan to keep online meetings as part of TSML. That has since changed, so we are looking as ways to improve TSML to handle both online and in-person meetings. Long term, I think we will also want to keep the ability to annotate a meeting location as temporarily closed. Again, that isn't a meeting _type_ per se, and we would like to change how we handle those. The current approach reflects the quick and dirty solution implemented to quickly address the realities of pandemic.  

We can also look at ways to improve the filtering process (the next release will restore the ability to select multiple types) or otherwise make it so users can more easily chose between online or in-person meetings.
