### ISSUE TITLE
Make the Plugin and Meeting Guide App Similar

### ISSUE THREAD

**Issue by ebart455987** [code4recovery/12-step-meeting-list#178]
**Is your feature request related to a problem? Please describe.**
The 12 Step Meeting List and the Meeting Guide App display differently.

**Describe the solution you'd like**
Please add Strike Through on the Locations  text for the 12 Step Meeting List, similar to the App.

**Describe alternatives you've considered**
None, this is merely a suggestion, a nice to have.

Thank You for everything you do - This is an awesome application to helping people find meetings. 
**Additional context**
![Crossed Out](https://user-images.githubusercontent.com/55007577/95695602-abb3f700-0c05-11eb-8ac2-f252c39cfdce.jpeg)

**Comment by tech2serve** [comment]
Thanks for the kind words.

What you're describing should already occur on the single meeting page. If not, we can reopen this issue as a support request.

On the meeting list page, we opted to gray out the addresses (thought it looked cleaner), but you are able to apply local css to your site that would strike them out instead of using graying. I tried to find an example at our old support site (Wordpress.org) but it didn't come up immediately. You might try searching more. Or, if you're a member of TIAA Forum, I believe the approach was discussed over there. 

If I come across it, I'll post it here and tag you.
