### ISSUE TITLE
Zoom Password 

### ISSUE THREAD

**Issue by keligirl43** [code4recovery/12-step-meeting-list#192]
I have one Zoom meeting that wants to use a password. I put it on our spreadsheet, but it's not showing up online or the meeting guide. Are we able to put meeting passwords on the spreadsheet?

**Comment by tech2serve** [comment]
Let's start with the meeting detail on the admin meeting page. If this all checks out, we'll look at the spreadsheet aspect (because, that really shouldn't be a factor).

The form for a Zoom link with a password should be:

`https://us04web.zoom.us/j/8983736284?pwd=WGJnRUNwZnpUSa9FS2FaRdJemFpyIi09`

The portion after the `pwd=` is the hash of the password, as it is generated by Zoom based on the passcode.

If you make sure link looks similar to that in the plugin, does it then work when you click on "Join Meeting"? 

Keep in mind, the password is not going to show up on the front end. We did that to help reduce the chance of someone using the information for Zoom Bombing. 

If this still doesn't work, please share some screen caps of what you're seeing, and tell me what you think you should be seeing.

Let me know.

**Comment by keligirl43** [comment]
Thanks for the quick reply. 
I looked at the link and this is it https://us04web.zoom.us/j/4807761248. 
I then looked at some of the other meeting links and they do have the pwd=. 
Do you know how to generate a link with the password in it? I can let the meeting leader know how to do it. 

Thank you!!

**Comment by tech2serve** [comment]
I know mine show up when I copy the meeting link in Zoom. The meeting leader will need to look closer in their Zoom app, but it should be there.

I'm going to close this for now, but if you find you still have an issue after you get the full link, we can reopen the issue.

**Comment by keligirl43** [comment]
OK, thank you so much!
