### ISSUE TITLE
Bug with AJAX Request for Online Meeting

### ISSUE THREAD

**Issue by Carlsans** [code4recovery/12-step-meeting-list#196]
When clicking zoom link, nothing happen. The problem is intermittent and tested with many users. I caught it in chrome console. Note that other meeting worked.

[bug12smlajax.zip](https://github.com/code4recovery/12-step-meeting-list/files/5432272/bug12smlajax.zip)

**Comment by tech2serve** [comment]
Hi @Carlsans --

At this point, because this issue, as best I can tell, is specific to your site, I would ask that explore three things with your site:

1. Double-check the link you have entered for the Zoom meeting. Even post one here as an example.
1. If you have site-wide cache you can clear, please do so and see if the problem is resolved.
1. Disable other plugins to see if deactivating one of them clears the issue up. 

I'm not saying with certainty that you haven't found an issue with the plugin; just that we've not had other issues like this reported so we need to try and confirm a few points with your site.

Also, what version of the plugin are you running?

**Comment by tech2serve** [comment]
Haven't heard back from @Carlsans. If the OP returns, we can reopen the issue.
