### ISSUE TITLE
Wheelchair Location Information 

### ISSUE THREAD

**Issue by ebart455987** [code4recovery/12-step-meeting-list#199]
"Wheelchair Access" and "Wheelchair-Accessible Bathroom" are listed under meeting types.  
It would serve better listed under Location Information.  Entered once for the location, instead of entering for each meeting.   

Keep up the great work, appreciate everything you do for the program.

**Comment by tech2serve** [comment]
Hi @ebart455987,

We've been trying to triage and work on some of the issues we originally accepted as new features, and our team discussed this one today. 

In considering your request, we realized there are situations where multiple meetings might be at the same location, but because of the rooms/buildings used, only some of the meetings are actually wheelchair accessible. This isn't hypothetical; one of our members manages meetings for which this exact scenario is true. So, we decided that leaving wheelchair accessibility as tracked by meeting vice location gives webmasters more flexibility.

Although I'm going to close this issue, we're not closing the door on the conversation. One of our future initiatives is to rework meeting types to extract some of the information that doesn't really fit there. In some cases, I'd like to see accessibility pulled out as a type and to have it tracked separately. You may still see changes regarding this in the future.

I hope this makes sense, and if you'd like us to reconsider, please don't hesitate to comment.
