### ISSUE TITLE
Al-Anon Open and Closed wording change

### ISSUE THREAD

**Issue by district6wc** [code4recovery/12-step-meeting-list#200]
**Is your feature request related to a problem? Please describe.**
Wording change for Open and Closed meeting type for Alanon groups
**Describe the solution you'd like**
To 12-meeting guide application,

I am creating website for Al-Anon users and am using the 12 step meeting guide plug-in and would like to know if the wording can be changed for Open and Closed description for the meeting types.

Here is the new language 
- instead of closed 
Meetings for friends and families of Alcoholics
-Instead of open - Observers, friends and families of alcoholics welcome 

Again,  This is for Al-Anon meetings only.  

I have some coding experience and would like to know if this is something I can change?

**Describe alternatives you've considered**

**Additional context**

**Comment by district6wc** [comment]
Please email reply to sholopainen@triad.rr.com or districtws@gmail.com.

**Comment by tech2serve** [comment]
Hey @district6wc,

It sounds like you don't have Al-Anon selected as the program type under settings:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/31904316/97608500-6ef74680-19e0-11eb-9488-d9a8dda23e72.png">

If you're still wanting to make changes, you can create your own customized type. Please see the FAQ for this.

Please let us know if this resolves the issue.

**Comment by district6wc** [comment]
Yes I do have alanon selected as the meeting type

Thank you for your help!

**Comment by tech2serve** [comment]
On my dev site, with Al-Anon selected, the wording that shows up currently is very similar to what you've proposed:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/31904316/97629039-8263db00-19fb-11eb-8880-564e0009b550.png">

I don't see any public reference to Open or Closed.

If you're not seeing something similar to that, then something else is amiss. 

If you're still interested in seeing something else, I suggest exploring the custom types.

**Comment by district6wc** [comment]
Here is the wording for Closed .  Apparently the second highlighted wording
is incorrect.  Is there a way that could be changed?  I know it is similar.

Example below:

[image: image.png]

Yours in Service,
Stephanie Holopainen
Learning To Live AFG, Graham

District 6 Website Coordinator Panel 59
336 675-1301

**Comment by tech2serve** [comment]
I'm not sure why, but your image didn't come through. Usually I just drag and drop them onto the message. You can check preview to make sure it uploads correctly.

In any case, the wording being used has been in place for a number of years and it used by other Al-Anon websites so I don't see a need to change the wording for everyone. In my research, the wording seems to reflect what most Al-Anon communities consider as appropriate for Closed Al-Anon meetings.

>Is there a way that could be changed?

Yes! The [FAQ Entry here](https://github.com/code4recovery/12-step-meeting-list/wiki/Frequently-Asked-Questions#my-meeting-type-isnt-listed) describes how to modify the `functions.php` to include the custom/changed type. 

Also please note it is considered a Wordpress best practice to make a child theme for your site, and to use the child as the place to put your customizations. You want to do this so that every time we update the plugin, you're not having to reapply your changes. Please search the Internet for how to do this. There may also be some plugins that support this, but I haven't researched them and can't make and recommendations.

Good luck!

Tim

**Comment by district6wc** [comment]
Thank you!

Yours in Service,
Stephanie Holopainen
Learning To Live AFG, Graham

District 6 Website Coordinator Panel 59
336 675-1301

**Comment by district6wc** [comment]
I'd like to reopen this inquiry:

Has this been resolved? I have members asking about updating to align with WSO site comments:

The Al-Anon Meeting Type designation, which previously referred to whether
the meeting was open to visitors or closed to attendance by members only,
often confused members and newcomers. It has been replaced by the term
Meeting Attendees, and the options have been changed to* “**Families and
Friends Only***” and *“**Families, Friends, and Observers Welcome**” *

I am not seeing where the verbiage is on the function.php file, can I get some clarification?

Best Regards

Rose Lanaro
District 6
