### ISSUE TITLE
Filter Out Suspended Meetings

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#216]
COVID-19 is not going away any time soon :( and we need a way to filter out meetings that are typed as "Location Temporarily Closed" from meetings that are online, yet will someday return to their former location in-person. 

Unmarking "Location Temporarily Closed" makes the meeting look at first glance as if were a hybrid meeting because the meeting is only meeting online. 

I like that the location is greyed out for meetings that are not meeting at their previously designated location, and that there is a green online tag and when looking at meeting detail, the location is crossed out, but we need a way to filter out suspended meetings. 

There are basically 6 types of meetings:
1. **Location Closed, but meeting online**: currently designated by checking "Location Temporarily Closed " type and entering URL. 
2. **Location Open and meeting online (hybrid)**: currently entering URL and appending meeting name with Hybrid
3. **Location Closed, and SUSPENDED**: currently designated by checking "Location Temporarily Closed " type and appending name with SUSPENDED.
4. **Online Only, and never met in person:** Currently entering URL and putting our county and state in address field. 
5. **Outdoor only at closed in-person location**: Currently checking outdoor type and appending name with Outside.
6. Reopened indoor meetings: Currently adding the text "reopened" somewhere in the location or meeting notes.

There should be a way to return everything above, and filter out #3 as listed above. 
 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tech2serve** [comment]
Duplicates #171, #153, and others. This will be addressed as soon as possible. Getting "approximate location" working is a step in that direction.

My intention is to add "attendance option" for each meeting which will be one of three values ("In-person", "Online only", "In-person and Online"). Still evaluating how to handle outdoor (I think leaving it in notes would have been adequate, and so this may be removed as a type in future versions, or we may have a draggable pin showing the outdoor location).

For the location, we recognize a need to extract this status information from meeting type (because it isn't a meeting type) and to add better support for managing the location itself.

**Comment by Grateful-Viv** [comment]
The intention was to filter out Location Closed, and SUSPENDED meetings to they don't show up by default unless specified.

**Comment by tech2serve** [comment]
Understood. All part of the same though since Wordpress doesn't let us search by a NOT. Getting "Online" and "Location Temporarily Closed" removed from the type and into different data forms will let us achieve the kind of filtering we know people want..
