### ISSUE TITLE
Beta Test V3.9.4-rc

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#235]
Related to Issue [#132](https://github.com/code4recovery/12-step-meeting-list/issues/132) in which I created a test meeting and tried to duplicate the behavior described... 

I entered some meeting info in a new meeting and then typed in "test location" in the location field. After saving as a draft, the text in the location field was no longer there. I then typed in an approximate location using our county and state in the address field. I already had several meetings in the database using this address with the location name as "Online Meeting". As soon as I did that, it changed the location name to "test location" for all meetings associated with the county & state. 

So I went back and corrected the name for one of the "online meeting" location names, and the rest were adjusted. This tells me the location name is associated with the address, even if it isn't an actual street address.

I went back to the test meeting and just put in the state (no county) and the draft meeting saved. I also then took out the location name, and still could save the draft. What isn't good is it displays when previewing the meeting as "there is -1 other meetings at this location" which makes no sense. Also the map makes no sense either and I am not sure why it is even necessary for an online meeting. Doing something like Atlanta has (I know it's not WordPress) makes more sense. Instead of a map, it simply shows an image saying it's a virtual meeting. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tim-rohrer** [comment]
> Related to Issue [#132](https://github.com/code4recovery/12-step-meeting-list/issues/132) in which I created a test meeting and tried to duplicate the behavior described...
> 
> I entered some meeting info in a new meeting and then typed in "test location" in the location field. After saving as a draft, the text in the location field was no longer there. I then typed in an approximate location using our county and state in the address field. I already had several meetings in the database using this address with the location name as "Online Meeting". As soon as I did that, it changed the location name to "test location" for all meetings associated with the county & state.
> 
> So I went back and corrected the name for one of the "online meeting" location names, and the rest were adjusted. This tells me the location name is associated with the address, even if it isn't an actual street address.

It sounds like that is the correct behavior, unless you're saying the location name changed for _all_ addresses in that city and state? We don't want to have multiple location names for the same address, be it approximate or not. Nor do we want to have a single location name match multiple addresses. Both situations would be confusing. We want locations to be unique.

After you saved a draft, did you navigate to a new page and then start the entry of a new meeting? If so, when you tried to type "Test L..." did it show up as one of the meeting options?
 
> 
> I went back to the test meeting and just put in the state (no county) and the draft meeting saved. I also then took out the location name, and still could save the draft. What isn't good is it displays when previewing the meeting as "there is -1 other meetings at this location" which makes no sense. Also the map makes no sense either and I am not sure why it is even necessary for an online meeting. Doing something like Atlanta has (I know it's not WordPress) makes more sense. Instead of a map, it simply shows an image saying it's a virtual meeting.

We should look the issue of state only closer. I don't think that should be accepted. I think the user should be required to put in a minimum of a city/township and the state. Thoughts?

I may look at the idea of displaying something other than a map later, but it is pretty low priority. I don't think it creates confusion (since there is no marker) as it is, and adding some other image, imo, adds code complication without significant value. I guess it might make it clearer, so I'm not opposed. 

Did you experience any issues with directions not showing up when you expected them to? Or vice versa?

**Comment by tech2serve** [comment]
> Related to Issue #132 in which I created a test meeting and tried to duplicate the behavior described...
> 
> I entered some meeting info in a new meeting and then typed in "test location" in the location field. After saving as a draft, the text in the location field was no longer there. I then typed in an approximate location using our county and state in the address field. I already had several meetings in the database using this address with the location name as "Online Meeting". As soon as I did that, it changed the location name to "test location" for all meetings associated with the county & state.
> 
> So I went back and corrected the name for one of the "online meeting" location names, and the rest were adjusted. This tells me the location name is associated with the address, even if it isn't an actual street address.

It sounds like that is the correct behavior, unless you're saying the location name changed for all addresses in that city and state? We don't want to have multiple location names for the same address, be it approximate or not. Nor do we want to have a single location name match multiple addresses. Both situations would be confusing. We want locations to be unique.

After you saved a draft, did you navigate to a new page and then start the entry of a new meeting? If so, when you tried to type "Test L..." did it show up as one of the meeting options?

> I went back to the test meeting and just put in the state (no county) and the draft meeting saved. I also then took out the location name, and still could save the draft. What isn't good is it displays when previewing the meeting as "there is -1 other meetings at this location" which makes no sense. Also the map makes no sense either and I am not sure why it is even necessary for an online meeting. Doing something like Atlanta has (I know it's not WordPress) makes more sense. Instead of a map, it simply shows an image saying it's a virtual meeting.

We should look the issue of state only closer. I don't think that should be accepted. I think the user should be required to put in a minimum of a city/township and the state. Thoughts?

I may look at the idea of displaying something other than a map later, but it is pretty low priority. I don't think it creates confusion (since there is no marker) as it is, and adding some other image, imo, adds code complication without significant value. I guess it might make it clearer, so I'm not opposed.

Did you experience any issues with directions not showing up when you expected them to? Or vice versa?

**Comment by Grateful-Viv** [comment]
Apologies for not getting back sooner. Had some health concerns that needed tending too. Will try to get back to this over the weekend, if not sooner. Thank you.

**Comment by tech2serve** [comment]
No problem, and I hope you're doing okay. I'll be trying to put together `rc.2` this weekend.

**Comment by tech2serve** [comment]
Hey @Grateful-Viv.

Since we released v3.9.4, I'm going to close this. If there is still a direct issue, we can reopen it or create a new issue as is more appropriate.

Thanks for your help.
