### ISSUE TITLE
How can I change the Regions column heading to Districts?

### ISSUE THREAD

**Issue by VickiB11** [code4recovery/12-step-meeting-list#238]
First of all, thank you so much for all you do!  I'm a grateful member of Al-Anon who is doing service by using the 12 Step Meeting List to show the meeting listings for my Area.  Since we don't have Regions, I'd like to change that column heading to Districts and add the District numbers in it.  
Also, how do I make the Search optional with a drop down for Meeting Name, Location, or City-if that's possible.

Thanks for your help with this!
Vicki B

**Comment by tech2serve** [comment]
Hi @VickiB11 --

The only support TSML provides for this is from the "area" filter button:

<img width="182" alt="image" src="https://user-images.githubusercontent.com/31904316/100680949-4abcbb80-3338-11eb-92cd-5a1efb9ab85e.png">

When you see "Switch to Districts", click that and you'll see the display switch. Then select the district you want to show in the meeting list. If you don't see "Switch to Districts", it is because you don't have any districts defined with groups/meetings attached to them.

Whatever district you select should persist while the session is open, but will reset for the next user/use. So, you may want to consider duplicating your districts into your regions if you don't use the latter. Regions can be however you chose to define them.

Beyond that, you'd have to jump into the code :-)

As far as the search goes, there is no way to make the it drop down beyond the auto suggestion behavior that exists. So if you start type the name of a meeting location or region (which could a district name if you choose), those will show up in the suggestions. If you keep typing or hit enter without selecting from the suggestions, a search will be done of meeting names, city, address, etc., and meetings will filter on this. That can be a little slow at times based on amount of data and search, so be patient.

I'm going to close issue as I believe I've answered your questions. If not, let me know (and we can reopen if necessary).

**Comment by VickiB11** [comment]
Thanks!
