### ISSUE TITLE
In Person Meetings

### ISSUE THREAD

**Issue by JonCincy** [code4recovery/12-step-meeting-list#239]
The problems is there is no way to filter as search for face to face meetings. You can filter only closed, open, newcomer, online meeting, etc. You may use the “Location Temporarily Closed” but who would want as list of meetings that are not meeting. Still this meeting type serves a viable service. However, there is no way I know to show only meetings that are meeting in person. Perhaps we need a new type named “In Person” or “Face to Face” or something that could be used to search for in person meetings. 
Locally we’ve added a note (Now meeting face to face) for in person meetings. Then we can search for the word “face” but there’s got to be a better way. I’m sure you folks are smart enough to figure this out. It looks like this pandemic will be with us for a while.

**Comment by tech2serve** [comment]
This question has been covered multiple times in other issues. Please search the issues for more details.

The gist today is that any meeting not labeled otherwise in an in-person meeting. And that Wordpress doesn't readily allow for searching for NOT something (i.e., I can search for all meetings not labeled as online.)

We are trying (but need to resolve a handful of issues first) to add more data fields to reflect meeting attendance options that will improve search.

**Comment by JonCincy** [comment]
Thank you.

 

Jon Secrist, Office Mgr.

Greater Cincinnati Central Service Office

513-351-0422
