### ISSUE TITLE
Meeting export function not working

### ISSUE THREAD

**Issue by namdrino** [code4recovery/12-step-meeting-list#248]
When I try to export the meeting list as CSV from the admin page it just hangs...nothing ever downloads.  This feature used to work but for some reason no longer does. I tried in 2 different browsers.  Any ideas? What other info is needed for someone to help with this?  THANKS!

**Comment by tech2serve** [comment]
If you have a lot of meetings, the process might take a couple of minutes.

In general, the standard troubleshooting steps should be tried. These include:

1. Make sure you're using the latest versions of Wordpress and TSML.
1. Open a development console and look for errors.
1. Disable all other plugins and re-test.
1. Clear the server cache.

**Comment by namdrino** [comment]
Thanks for the quick response.   I tried the steps above to no avail, but oddly enough, when I installed the WP PHP Console plugin it worked.  To test further I deactivated the plugin and it quit working again.... re-activated, now it works.

**Comment by tech2serve** [comment]
What is the stock version of PHP provided by your hosting site?

**Comment by namdrino** [comment]
7.3

**Comment by tech2serve** [comment]
@namdrino 

Are you still good? Is the export working?

**Comment by namdrino** [comment]
Hi - yes, as long as I use the trick I mentioned earlier.  Thanks!

**Comment by tech2serve** [comment]
Ok. I'm going to close this, but we can reopen later or start a new issue if necessary.

Since I've not heard of this issue before, and the solution you found eludes me intellectually :-), you may want to talk with your hosting provider to see if they have an idea of what is wrong with the PHP they have installed.

Or, hopefully, your solution will continue to work.
