### ISSUE TITLE
Meeting Format link

### ISSUE THREAD

**Issue by district6wc** [code4recovery/12-step-meeting-list#263]
I don't see a place in the app to add a meeting format document.  Is it possible to change one of the current button labels to be called Meeting Format?

Currently, I am adding a link under to Contact Information as a workaround.

 Meeting formats - Right now, people have to go to the "contact us" section to get the meeting formats.   Is it possible to relabel this section from "contact us" to "meeting format."

**Comment by tech2serve** [comment]
What do you mean by "meeting format"? We have types which include the common meeting formats (as I interpret the term).

Adding a screen cap of what you're looking at would also be helpful. One area I'm not clear about what you're asking is whether the issue is on the single meeting page or the admin side?

In general, we don't provide a way to relabel displays, but if you're talking about flagging a type (like we do for Men's meetings or Open), then there may be a workaround. 

I'm just not clear enough yet on what you're asking.

**Comment by district6wc** [comment]
[image: image.png]

This is a picture of the admin side.   I'm not trying to flag a type, just
wanted to know if I could change or add something to reflect that it is a
meeting format (which is a document groups use to chair or moderate a
meeting).

Does this help?

Yours in Service,
Stephanie Holopainen
Learning To Live AFG, Graham

District 6 Website Coordinator Panel 59
336 675-1301

**Comment by tech2serve** [comment]
The image didn't come through (you can test using preview before you post the comment), but the explanation helps. Thank you.

Not sure I have the solution you want to hear, but we really don't provide a way for that to happen. Some websites will have a separate documents section (plugin or just links to uploaded documents). Then in the meeting notes you could provide the title of the meeting format document. This would probably be your best bet.
