### ISSUE TITLE
11th Step Meetings encoded incorrectly when imported via csv file

### ISSUE THREAD

**Issue by crispyatl** [code4recovery/12-step-meeting-list#268]
In short, when you add a meeting through the web interface, the 11th Step Meeting code is stored as a string, but when you import it from a csv, it is stored as an int.  This explains why only certain sites are affected by the issue: It occurs in the very specific corner case that an 11th Step Meeting is imported from a csv file.

This is the root cause of related issue #257.  While PR #267 is now available to work around the issue, arguably the code that loads the csv should also be fixed.

If you add an 11th Step Meditation meeting in the web interface, it looks like this in the DB:
```
mysql> select meta_value from wp_postmeta where meta_id = 31737;
+---------------------------------+
| meta_value                      |
+---------------------------------+
| a:2:{i:0;s:1:"O";i:1;s:2:"11";} |
+---------------------------------+
1 row in set (0.00 sec)
```

However, if you import an 11th Step Meditation meeting from a csv file, it looks like this:
```
mysql> select meta_value from wp_postmeta where meta_id = 31763;
+-----------------------------+
| meta_value                  |
+-----------------------------+
| a:2:{i:0;s:1:"O";i:1;i:11;} |
+-----------------------------+
1 row in set (0.00 sec)
```

**Comment by apresence** [comment]
This fix is too specific, and could introduce unexpected results. That is, it is checking the meeting types for the string "11", but not specifically that, so anything might match like "welike11typesofmusic". The approach is a good idea though. I'd suggest making it more generic: Simply walk through the meeting type arrays and convert anything that's not a string to a string rather than looking for 11 specifically.

**Comment by joshreisner** [comment]
i'm going to close this - i feel like unless we get a report from the field that this caused an error that it isn't worth making an automated SQL update
