### ISSUE TITLE
Alanon meeting type description needs changing

### ISSUE THREAD

**Issue by district6wc** [code4recovery/12-step-meeting-list#274]
**Is your feature request related to a problem? Please describe.**
I am getting several requests that the description for open and closed meetings is incorrect for the Al-anon Program.   remove the old "Closed Meetings" and "Members"(now "Attendees") language above, changing it to something like "This meeting welcomes anyone who feels their life has been affected by alcoholism in a family member or friend.”

**Describe the solution you'd like**
Below is the WSO write up regarding this issue:
https://al-anon.org/blog/new-way-to-designate-closed-and-open-meetings/
The Al-Anon Meeting Type designation, which previously referred to whether the meeting was open to visitors or closed to attendance by members only, often confused members and newcomers. It has been replaced by the term **Meeting Attendees**, and the options have been changed to “Families and Friends Only” and “Families, Friends, and Observers Welcome” on the WSO Group Records Forms.

These new descriptions match the wording approved by the Board of Trustees at their **April 2019** meeting. The language is consistent with the Al-Anon spiritual principles of confidentiality and anonymity. The new terms were designed to be clearer to new members and more welcoming to both new and potential new members and professionals seeking to understand our program. For more information about the decision.

**Describe alternatives you've considered**
Would it be possible to allow the owner of the Al-Anon website to change the wording on the website that is maintained by each district?  For instance, I would like to be able to make this correction to be in alignment with WSO.

**Additional context**

**Comment by tech2serve** [comment]
How is this different than the duplicate issue #200 you entered in October?

Please include a link to your website.

**Comment by district6wc** [comment]
Hello,  Issue is not different, It still needs to be corrected for the
Al-Anon program!!

https://alanonalateen6nc.org/meetings/

I think it is the "Closed" verbiage that is not consistent with the WSO.

Yours in Service,
Stephanie Holopainen
Learning To Live AFG, Graham

District 6 Website Coordinator Panel 59
336 675-1301

**Comment by tech2serve** [comment]
On the public facing side or just in the edit meeting page?

**Comment by tech2serve** [comment]
Is this what you're taking issue with?

<img width="232" alt="image" src="https://user-images.githubusercontent.com/31904316/106338307-75a48c80-6261-11eb-9036-64073f870990.png">

And you think this should say "This meeting welcomes anyone who feels their life has been affected by alcoholism in a family member or friend."

and ...

<img width="234" alt="image" src="https://user-images.githubusercontent.com/31904316/106337991-bd76e400-6260-11eb-8766-0598471081c8.png">

Which should say "Attendance at this meeting is limited to members"?

Just so long as we remove the words "open" or "closed"? 

Since you might not be able to tell this from my written word, I'll share that I'm hesitant to get into a game of tweaking words; We'll likely never be able to make everyone happy (nor is that my job in my recovery :-) ).

Even as I tried to come up with wording, I got confused because your wording above seems even broader than WSOs. As I read WSOs, I can picture something very simple:

For the meeting with type Family, Friends and Observers, we can use:

"Attendees can be family members, friends or observers of those affected by alcoholism"

And for Family and Friends Only:

"Attendance is limited to family members and friends of alcoholics"

If you have a network of Al-Anon webmasters using TSML, perhaps you can run this by them and get consensus before we make changes?

**Comment by district6wc** [comment]
Thank you,  let me check with my district and other websites.  I'm copying
other members for their input as well

**Comment by district6wc** [comment]
in the edit page

Yours in Service,
Stephanie Holopainen
Learning To Live AFG, Graham

District 6 Website Coordinator Panel 59
336 675-1301

**Comment by district6wc** [comment]
I;m sorry replied to wrong email thread.  The wording should be changed on
public facing side

Yours in Service,
Stephanie Holopainen
Learning To Live AFG, Graham

District 6 Website Coordinator Panel 59
336 675-1301

**Comment by 97eighty** [comment]
Revisiting this issue. @district6wc  Is this still an issue with AL-ANON?

If so, can you update the exact descriptions for each of the items below? 

**Default descriptions:**

'type_descriptions' => [

'C' => __('Closed Meetings are limited to members and prospective members. These are persons who feel their lives have been or are being affected by alcoholism in a family member or friend.', '12-step-meeting-list'),
'O' => __('Open to anyone interested in the family disease of alcoholism. Some groups invite members of the professional community to hear how the Al-Anon program aids in recovery.', '12-step-meeting-list'),
			],	
**Default Types:**

'O' => __('Families Friends and Observers Welcome', '12-step-meeting-list'),
'C' => __('Families and Friends Only', '12-step-meeting-list'),

**Comment by district6wc** [comment]
Yes,  this is still an issue.   Thank you.   I will send update

**Comment by district6wc** [comment]
Hello,

I am getting the wording verified by other members, but wanted to send the
below excerpt from the WSO website.  The type is correct.  I have those in
*bold*

The Al-Anon Meeting Type designation, which previously referred to whether
the meeting was open to visitors or closed to attendance by members only,
often confused members and newcomers. It has been replaced by the term
Meeting Attendees, and the options have been changed to* “Families and
Friends Only*” and *“Families, Friends, and Observers Welcome” *

Yours in Service,
Stephanie Holopainen
Learning To Live AFG, Graham

District 6 Website Coordinator Panel 59
336 675-1301

**Comment by 97eighty** [comment]
Hi @district6wc  To prevent going back and forth, can you edit these two descriptions?

Closed Meetings are limited to members and prospective members. These are persons who feel their lives have been or are being affected by alcoholism in a family member or friend.

Open to anyone interested in the family disease of alcoholism. Some groups invite members of the professional community to hear how the Al-Anon program aids in recovery.

**Comment by 97eighty** [comment]
Feel free to reopen when the correct verbiage is agreed upon.
