### ISSUE TITLE
Is it possible to restrict the search autocomplete to one country only?

### ISSUE THREAD

**Issue by aavictoria99** [code4recovery/12-step-meeting-list#278]
I am website administrator for AA Victoria in Melbourne, Australia. Love this plugin, it has made my job so much easier. Please carry on 'keeping it simple'. The search box doesn't allow the user to see the autocomplete fully so we get locations in the wrong Countries! Is it possible to restrict the search autocomplete to one country only?

**Comment by tech2serve** [comment]
Are you talking about the address field on the Edit Meeting page?

**Comment by aavictoria99** [comment]
See attached screenshot
![Screenshot1](https://user-images.githubusercontent.com/78445180/106828393-3ef5c880-66de-11eb-8d79-8e19537bd557.jpg)

**Comment by tech2serve** [comment]
I'm trying to duplicate the issue. 

First off, the search on the front end *should* only be searching existing meeting information. 

Second, when I try entering "Newport" and choosing search on your website, I'm getting

<img width="942" alt="image" src="https://user-images.githubusercontent.com/31904316/106829217-b46b8580-6659-11eb-88be-da3d00d8abe2.png">

If I type "sale" into your search field, and click search, I get this:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/31904316/106829334-f1377c80-6659-11eb-8108-9833c1942aec.png">

This is the behavior I would expect to see. If you're not seeing this, we need to explore deeper.

What version of TSML do you have installed? 
What version of Wordpress?
What browser are you using?
What other browsers have you tried?
Provide some screen caps showing the exact results you're seeing.
 
Let's start with that. 

Thanks.

**Comment by aavictoria99** [comment]
Thank you for all your help.
TSML Version 3.9.6
Wordpress 5.6.1
Firefox 85.0

If you type in 'Newport' and then search if you place the cursor back in the search bar you will see it has auto-filled by Google as:
Newport, RI, USA. So obviously we don't have a meeting there. The size of the font and the search box means that the member cannot see that Newport, RI, USA has been selected for him. Typing in 'Sale' works because there isn't a 'Sale' in the USA therefore auto-fill just finds the Australian Sale. Maybe it is best to keep it simple and I will let people know that when typing in an address they do 'Newport,Vic' etc.

**Comment by aavictoria99** [comment]
One thing that would help would be able to alter the default radius setting to 10 KM.
I have tried following instructions to edit function.php but I cannot find the right file to edit.
Best regards

**Comment by tech2serve** [comment]
There are a couple of locations with the word “Sale” in them in the US, and Mexico, and the UK. But, since that word isn’t in your meeting list, it doesn’t show in results.

I just tried from another device (iPad using Safari), and Firefox and Chrome and I am still unable to duplicate what you’re seeing. So I’m convinced at this stage that your issue is something unique on your end.

The behavior you’re describing sounds like browser autofill/autocomplete, and so you may investigate how to turn that off or clear any cache/stored answers for your browser, or try another browser/computer. 

I want to reiterate that, unless I really goofed something up when I rewrote the code for this, the search being done on the front end is only of actual meeting data from your site. This search box doesn’t go to Google maps or anywhere else to do the search. Only the meeting data in your site. And the results should show like I demonstrated with “Sale” above.

The backend (Meeting Edit page) is different. We do query Google maps (well, soon to be our own api-gateway) to geocode addresses. I think it is quite possible that “Newport, RI” got entered at some point in the past on your computer, and that is being remembered by your browser which is why it is showing up on the front end. I believe if you clear you history/cache/autofill/complete, your problem should be resolved.

As far as a search radius, we do that. When a location is entered in a system, geometric points around it are captured and sent along with future geocode requests. While Google won’t only exclude results from that defined box, the results are biased to the area. So far, this has worked pretty well, and I believe it still is.

And because I can’t reproduce what you’re seeing from my browser using your website, I don’t believe the issue is with the geometric bounds or your database. Let’s focus in on your browser first, and see if clearing its memory solves the problem.

**Comment by aavictoria99** [comment]
Hi tech2serve
What country are you accessing site from?

**Comment by tech2serve** [comment]
The US.

**Comment by aavictoria99** [comment]
Hi tech2serve

I am accessing the AA Victoria website using Opera from US in California using my VPN.

This is what I see:

![Github-278-Screen-1](https://user-images.githubusercontent.com/78445180/107158943-2c7ed600-69e1-11eb-8efb-64a0b68a0174.jpg)

I change Day Setting to Any Day and type in 'Newport' into search bar and this is what I see:

![Github-278-Screen-2](https://user-images.githubusercontent.com/78445180/107159011-aa42e180-69e1-11eb-9088-e1416ac5ef4f.jpg)

If I click on down arrow and select 'Near Location' I still get the same screen.

If I place my cursor in the search box and scroll along to the end I can see it has selected:
'Newport, RI, USA'

If I type in Newport,Vic into the search bar and select 'Near Location' this is what I see:

![Github-278-Screen-3](https://user-images.githubusercontent.com/78445180/107159244-e6c30d00-69e2-11eb-9bb8-3c860cc4d8fa.jpg)

This is now finding the nearest meeting correctly.

If I place my cursor in the search box and scroll along to the end I can see it has selected:
'Newport VIC 3015, Australia'

That is why it would  be good to restrict autocomplete to just Australia for our website. But maybe that is not possible with the Google API.

Thanks again for all your help.

**Comment by tech2serve** [comment]
Ok, I can duplicate the issue when using searching near location and following your steps above. Based on your earlier comments, I focused in on regular search and no a search "near location".

**Comment by 97eighty** [comment]
Appears possible to restrict by Country using setComponentRestrictions method.

autocomplete.setComponentRestrictions({
    country: ["au", "us"],
 });

**Comment by joshreisner** [comment]
Hey! So Google has something called a "places autocomplete" but this is not that -- this is a normal geocoding request. If you type in "Newport" into the search then TSML will geocode that and save it to the cache. 

When you search the Google Geocoding API for "Newport" with no other parameters it returns two results, the first in Rhode Island and the second in Tennessee. Your network location is not relevant, so a VPN won't affect this.

There are options that can be passed to the geocoder. We have code in our `tsml_geocode_google` function to bias the geocoder to the map viewport, they are here: https://github.com/code4recovery/12-step-meeting-list/blob/4a4b530c692319cf020315abe9c6219f04f37654/includes/functions.php#L634-L637

I would first check to make sure that is working. Another option would be to look into region biasing, in this case finding an option to pass `&region=au` to the geocoder. More info on that is here: https://developers.google.com/maps/documentation/geocoding/requests-geocoding#RegionCodes

Are you using Google as your geocoder? It might be good to clear your geocoding cache and see if you can capture the URL of the geocoding request that's fired to see what exactly is getting sent.

**Comment by aavictoria99** [comment]
Thanks everyone for your help. It seems to be OK for now.
