### ISSUE TITLE
Meetings Not showing Up On Meeting Guide App

### ISSUE THREAD

**Issue by district43aa** [code4recovery/12-step-meeting-list#285]
Hi good morning 
I have three meetings from the same area that I am having problems with not showing up on the meeting guide app. One of them I sort of rectified by taking out the building number and only put the street and postal code. The other two are not showing up. I have googled all three to make sure I have the correct address but don't seem to want to list. They are populating on our website but won't seem to show on the app. Are you able to contact me by phone? 604-916-4500
Darren

These are the meetings:
[Www.district43aa.org/meetings/cloverdale-crowd]()
[Www.district43aa.org/meetings/Saturday-night-coffee]()

[www.district43aa.org/meetings/ladies-big-book-meeting-new-night]()

**Comment by tech2serve** [comment]
Hi Darren,

Please start by checking a couple of things with each of those three meetings:

1) Check the online conference URL and make sure it is valid. By valid, it should look something like "https://www.zoom.us/j/<meetingid>" . You should be able to copy and paste the contents to a browser window, and open the meeting.
2) Confirm the address is complete without inappropriate characters. At a minimum, it should have what we would call city and state. I think city and provinces in your neck of the woods? In any case, if the address geocodes and the meeting publishes, it should be okay. 

BTW, what version of TSML are you using? If v3.10.0, are you experimenting with our beta api gateway? 

Most often though, in these situations, the meetings in question are really close to whatever AAWS/GSO has set up for the geographical boundaries for the reporting entity (maybe because another district shares those meetings or is close by?).

If my suggestions above don't help, you'll probably have to contact appsupport@gso.org to check that or otherwise resolve this. In general, if the meetings are correctly in the feed (which they should be if they're published and showing up on your site), then the issue is most likely with Meeting Guide.

Please keep us posted.

**Comment by district43aa** [comment]
HI Thank you for getting back to me.  I did update the plug-in to V3.10.0. as I was requested to in the email I received.  I have contacted appsuport at GSO to check out geo boundaries.  We do have a couple meetings that are in the area that are populating on the app, but one for sure is not updating and two are not showing up.  We have 4 meetings total in this area called Cloverdale / Surrey.  I have one of the meetings as the ‘Surrey Region’  as it is more in Surrey, BC and the other three I have in the ‘Cloverdale’ Region, which if memory serves me correct I created when I took over this position.

I have also recently added a google API code for the maps, and set up a billing account as it requested for it to work properly.

**Comment by district43aa** [comment]
I do know that I was having this issue before I added the API code. We had to move our site to a new host was going to tackle this issue when our site moved.

**Comment by tech2serve** [comment]
> HI Thank you for getting back to me. I did update the plug-in to V3.10.0. as I was requested to in the email I received. I have contacted appsuport at GSO to check out geo boundaries. We do have a couple meetings that are in the area that are populating on the app, but one for sure is not updating and two are not showing up. We have 4 meetings total in this area called Cloverdale / Surrey. I have one of the meetings as the ‘Surrey Region’ as it is more in Surrey, BC and the other three I have in the ‘Cloverdale’ Region, which if memory serves me correct I created when I took over this position. I have also recently added a google API code for the maps, and set up a billing account as it requested for it to work properly. 

So with v3.10.0, it is not necessary for you to use Google. You can use Mapbox, and either use our beta api gateway for geocoding or remain in "legacy" mode. In either case, I don't think that is the issue. I was just curious to ensure our beta api gateway wasn't an issue. Or, if you were using it, I could check out logs for anything out of the ordinary. Again, though, I don't think this is a factor with your issue as the addresses have successfully geocoded.

Since you didn't raise any concerns about the two steps I provided above, I will assume they both checked satisfactorily. Given this, and that you're not seeing any explicit errors on your side, I'll assume the issue with those meetings not showing up in Meeting Guide is on their side. I suggest continuing to work with them.

If they respond with anything that appears to be an error with the meeting feed from you, please let us know and we can reopen this issue.

**Comment by district43aa** [comment]
Oh I see about the API now.  This all new to me.  I have our API Code in but it is set for ‘Legacy Method’  So you are saying I don’t need to have the API code anymore with this new version and the maps will work for us?

**Comment by tech2serve** [comment]
Did you add your own Google API key to line 585 of functions.php? At this time, that is no longer required. If you had not created your own `functions.php` as part of a child theme, then updating to v3.10.0 overwrote any change you made anyway.

Given that you are using legacy, you are free to use Mapbox for mapping.

My apologies if there was confusion with this. We were struggling to keep from getting big charges from Google. Hopefully, we have that under control now :-P.

**Comment by district43aa** [comment]
Ok do I have to use map box or do I have to option to use my own google API if I have it linked to a payment account?

**Comment by district43aa** [comment]
My apologies I didn't answer your question. I did just get a API code about a month ago.  I signed up for a gmail account and filled out the billing portion in case we went over our allotment. Does. Is the maps on the app separate from the maps on our website?  Are you using google maps on the app?  Can we use google maps on the plug in if we have our own API code or do you still want us to use Mapbox?

**Comment by tech2serve** [comment]
You are free to use whatever approach works best for you. Most users do not want to set up a Google account (with credit card as you know), and using Mapbox (which only requires registration) is easier for them. 

It is helpful to understand that the plugin uses services for mapping and geocoding (two different functions). In any situation, the webmaster/org is responsible for the mapping API key (not API code), be it from Mapbox or Google. We (Code for Recovery) have chosen to be responsible (as much as we can) for the geocoding function. But, you the user, are welcome to enable geocoding on your own Google API key (that you also secure!) and use that in v3.10.0. If you do that, you could theoretically be charged because your key is being used for both functions on your site; however, it is EXTREMELY unlikely you would get over a the credit limit Google provides each month (currently $200). Code for Recovery went over in December primarily (in appears) only because of a bug on one of the websites using TSML (and we are supporting ~700 sites). That is why we're migrating towards an API gateway.

I want to add something very important here. Our goal is to make this easy for the users, and I'm already talking at a technogeek level that may be way beyond what you really want to know :-) This is why we try to simplify things and let users use Mapbox for the mapping while we take care of geocoding through our API gateway.

But that said, each website is free to use whatever they choose. And one more time :-) The easiest approach for most webmasters is to obtain and activate a Mapbox API key for mapping while using us for geocoding (either the beta api gateway or legacy setting). 

Mapping and geocoding in Meeting Guide is completely separate from TSML and your website. Your keys are only being used for TSML.
