### ISSUE TITLE
Al-Anon Types alteration/addition in Variable.php

### ISSUE THREAD

**Issue by playpusoffury** [code4recovery/12-step-meeting-list#290]
Please consider adding LBGTQ+ Type.
Consider removal of existing Types covered by above Type.

'LGBTQ' => __('LGBTQ+', '12-step-meeting-list'),

Additional items to Consider altering/adding:
'PG' => __('Parent/Grandparent Focus', '12-step-meeting-list'),
'WS' => __('Workshop Meeting', '12-step-meeting-list'),

For Future reopenings of physical meetings as COVID rules begin lightening up.
'SD' => __('Open with Social Distance Rules', '12-step-meeting-list'),

Appreciate everything this plugin has done for the community!

**Comment by tech2serve** [comment]
Hey @playpusoffury,

Since TSML, with program set to Al-Anon, isn't feeding a central meeting app like AA is, there is really no reason you can't use a child theme and the custom meeting types configuration to set types however you wish. 

Please see our FAQ under the Wiki page for steps on how to create your own meeting types. 

Creating a child theme for your website is beyond the scope or our help community here, but there are bunches of tutorials on Wordpress for how to do that.

Good luck!
