### ISSUE TITLE
Trying [tsml-react] - not working

### ISSUE THREAD

**Issue by jackieoh1** [code4recovery/12-step-meeting-list#310]
Greetings - 

I am wanting to take advantage of this feature and because i am already using the plugin, I tried simply typing in [tsml-react] on a page as suggested. 

Are there other steps I need to take to utilize this?  Thank you!
Jodie/Northern Michigan Central Office
nmcentraloffice.org

**Comment by joshreisner** [comment]
Hi @jackieoh1 - sorry that this was left for six months! The shortcode is `[tsml_react]` or `[tsml_ui]`, but not `[tsml-react]` (use an underscore instead of a hyphen).

Please let us know if you're still having problems with this an we'll try to get back to you more quickly next time.

Since you're using the 2014 theme on your site, you'll likely need some CSS to make it full-width. If you could wait a little, we'll have a new version soon with an easy way to toggle between appearances.
