### ISSUE TITLE
Add Active/Inactive Meeting Status

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#313]
Would like to be able to see all active meetings whether they're online, outside, in-doors, etc and not show inactive meetings (temp closed). Can you add this as another field instead of adding it as a type? 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tech2serve** [comment]
I'll formally add this to our list. 

We've already been discussing it, but it is lower priority as many of us feel users simply move meetings that have been suspended to a draft status, thus they don't show up. Others are still using TC. 

Tell me again your website, please.

How many of your meetings that went to TC because of the pandemic and started up again?

In the end, I suspect the approach you're asking for will win out. Two other meeting management apps I know of have or are implementing this. We'll still have to track TC in the feed for Meeting Guide I suspect.

**Comment by Grateful-Viv** [comment]
Website: sussexaa.org. We don’t have a lot of meetings compared to larger cities. We’re just a small beach town. 

I’d like to just display active meetings, but give folks an option to search or see their inactive meetings (which are updated as they move back inside, go online, or move outside as the weather improves). Putting these meetings in draft status means no one will see them. But I’d like to display by default all active meetings, including using the upcoming meetings widget we used to display on the sidebar. I’d also like to set up a query that displays inactive meetings, but because of the meetings where type is TC with a URL (to indicate online), these meetings also show up. 

We had at one point about 100 meetings that were suspended. Now we’re down to 38. 

I’d appreciate if this could be a higher priority and considered for implementation. 

Thanks.

**Comment by Grateful-Viv** [comment]
I know this isn't on the front burner, but I'm hoping you can do something soon with being able to add an active/inactive flag. 

Alternatively, please add online back as a type and then I can add that to my whitelist of meetings I want selected.

Otherwise, will have to go back to every meeting that has a URL and toggle off the temp suspended location type. That sounds like a PITA and plus, it is misleading since the meeting is not at the location.

**Comment by tech2serve** [comment]
The branch (#324) being worked for #312 will, I believe, essentially accomplish what you're asking for. 

There is still some discussion about how to handle meetings that are inactive because the meeting location is not available (i.e., what we've been calling temporarily closed.) Some users want to see them; some don't. 

Our goal is to have this in beta soon.

**Comment by tech2serve** [comment]
The new approach will track each meeting by online, in-person, temporarily closed (probably will rename this to temporarily inactive, or something similar) or hybrid: these options are mutually exclusive. This version effectively provides even more robust support for online only meetings. The admin will be able to create meeting lists showing online (with hybrids) or in-person. We're also looking at a simple list for meetings that aren't meeting, separate from the other lists.

TSMLui is already excluding inactive meetings from the list (or a dev version). You may wish to experiment with that?

You don't need to mark online only meetings as TC. Simply make sure the online meeting information is entered, and then put in an approximate address (i.e., city and state).

Yes you generally *should* use a child theme in order to do extensive customization, but there may be some plugins that help with that. 

Our FAQ documents how to add custom types for your site. They'll be ignored by Meeting Guide. I'm not sure we'll support indoor vs outdoor (beyond Outdoor already as a type) as this is something that can go in the notes and isn't really critical for people finding the meeting, but you can add Indoor as custom types if you wish.

**Comment by Grateful-Viv** [comment]
> The new approach will track each meeting by online, in-person, temporarily closed (probably will rename this to temporarily inactive, or something similar) or hybrid: these options are mutually exclusive. This version effectively provides even more robust support for online only meetings

That's outstanding. Thank you.

>TSMLui is already excluding inactive meetings from the list (or a dev version). You may wish to experiment with that?

Yes, already saw that. I opened a few threads over on the TSML-UI page. See https://github.com/code4recovery/tsml-ui/issues/110

>You don't need to mark online only meetings as TC. Simply make sure the online meeting information is entered, and then put in an approximate address (i.e., city and state).

That is the way I've been doing that. Using county and state which works great. 

>Yes you generally should use a child theme in order to do extensive customization, but there may be some plugins that help with that.

Be interested to know more about these plugins, but am willing to do children if needed. I am concerned they do not work in the Meeting App Guide. We have for example Beginners meetings that would be useful as a type. Same goes for Promises meetings.
