### ISSUE TITLE
Google Maps Showing Incorrect Page Loading

### ISSUE THREAD

**Issue by aavictoria99** [code4recovery/12-step-meeting-list#314]
Please see attached screenshot
![Screenshot-Google-Maps-Not-Working](https://user-images.githubusercontent.com/78445180/114252367-1775f180-99e8-11eb-992e-8c064f3e3616.jpg)

**Comment by tech2serve** [comment]
Check out some of the other Issues by searching with the word Google. 

You can also look in your developer console and you'll see the likely clue. Most likely is says invalid API key or something similar.

This issue is caused because something happened with your mapping API key for Google Maps. Or, you switched from Mapbox to Google but don't actually have a key set up?
