### ISSUE TITLE
Edit Page or Shortcode

### ISSUE THREAD

**Issue by manattweb** [code4recovery/12-step-meeting-list#32]
I'm new to the use of the plugin and after getting all of my data in, it created a page with an address that already existed. We had a header image and breadcrumbs that are now missing. Is there a way to edit the page that's created or use a short code to put the data display (table) on a page that we control?

**Comment by joshreisner** [comment]
Hi Steve, you can customize where the meetings page shows up, see the FAQ, I think it's at the bottom.

The header and breadcrumbs are up to your theme. Our archive page calls `get_header()` and `get_footer()` but some themes don't put the header image in there, and put it in the page template instead.

You're welcome to customize that page, see the FAQ on how to do that. I think it's called "overriding the template."

The meeting list itself isn't in a shortcode, that would be hard to do technically since it's not just one view, you need to be able to link back from all the sub-pages. We're looking at modernizing the plugin with a fully React-based system which might make that more possible, but it's not on the immediate horizon.

**Comment by manattweb** [comment]
Where are the FAQs?

**Comment by joshreisner** [comment]
The FAQ is at https://wordpress.org/plugins/12-step-meeting-list/
