### ISSUE TITLE
Unable to upload our meeting list (CSV file).

### ISSUE THREAD

**Issue by RhondaHoornstra** [code4recovery/12-step-meeting-list#322]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tech2serve** [comment]
Please fill out a more complete bug report and we'll be able to help you better.

I will say up front the plugin has not changed recently, and so if something worked but doesn't now, it is likely because something else changed. Either you updated another plugin that is causing a conflict, or you changed the CSV, etc.

**Comment by tech2serve** [comment]
Closed due to no response from OP.
