### ISSUE TITLE
Meetings not syncing after change in Plugin "Meeting Guide"

### ISSUE THREAD

**Issue by BerdieDesigns** [code4recovery/12-step-meeting-list#329]
After a year of using the Meeting Guide Plug in with no issues, after making changes to the list on the our site, "WordPress" the Meeting Guide App does not sync the changes. I've waited well over 4 days. area34district12.org
Thanks for any insight

**Comment by tech2serve** [comment]
Hi @BerdieDesigns,

We ask people to differentiate between the Meeting Guide App and the 12 Step Meeting List Plugin (TSML). The first is controlled by GSO and is an app that runs on mobile devices while the second is a community-maintained open source project providing a Wordpress plugin for use in maintaining meeting information. Understanding the difference helps users know where to get help. We can help you here with the plugin but cannot help you (much) with Meeting Guide.

In nearly all cases, when something was working, but has stopped, it is because something changed. Are you using the latest version of TSML? Wordpress?

Are the changes you've made showing correctly on your website's meeting list (https://area34district12.org/meetings/)? 

Are you experiencing any errors or warnings when you update information on your site?

Are none of the changes you've recently made showing up in Meeting Guide? Or just some changes? I ask this because we had a situation where a user entered online meeting information in the wrong field and didn't understand why the meeting didn't show up as online in Meeting Guide. 

In general, when there are no errors showing up in TSML, and changes are reflected in the user's website, but not in the app, the problem normally resides on the AAWS/GSO side (i.e., Meeting Guide). This assumes the site (i.e., area34district12.org) was registered with GSO. Please double check that your plugin's settings page reflects Meeting Guide as an authorized app. At this point, you'll need to contact GSO's support team at appsupport@aa.org. They may see something wrong with the feed coming from you, or it could be there is a conflict with a nearby reporting entity, or a number of other possible issues. Unfortunately, we the maintainers of the plugin aren't able to change or troubleshoot Meeting Guide issues.

Tim

**Comment by RBIWebsite** [comment]
I have a very similar issue. How do I set the plug in to "reflect Meeting Guide as an authorized app?

**Comment by joshreisner** [comment]
If specific information isn't syncing please let appsupport@aa.org know what it is and they can track down the issue. They can see if there are any errors importing your data and/or if there are conflicts with neighboring areas.

I took a quick peek and I don't see any of those issues happening, so my guess is it's been corrected.

For sure though please let them know the specifics, as in "on my website at this URL the meeting says X but in the app (screenshot attached) it says Y."
