### ISSUE TITLE
Types: Open

### ISSUE THREAD

**Issue by mochel23** [code4recovery/12-step-meeting-list#330]
**Is your feature request related to a problem? Please describe.**
The existing "Type: Open" makes a specific Open Meeting declaration: This meeting is open and may attend.

**Describe the solution you'd like**
Local members say that the actual declaration should be same as it is listed in the Big Book as well as on the Meeting Guide App.

**Describe alternatives you've considered**
Change the declaration to: "Open meetings are available to any one interested in alcoholics anonymous program of recovery from alcoholism non-alcoholics may attend open meetings as observers."
<img width="349" alt="Screen Shot 2021-05-04 at 3 01 07 PM" src="https://user-images.githubusercontent.com/69115383/117055806-96113680-ace9-11eb-844c-3502a888627d.png">

Should be: 

![IMG_7A49DD03C1D4-1](https://user-images.githubusercontent.com/69115383/117056034-da043b80-ace9-11eb-88d5-f9c44451dc83.jpeg)

**Additional context**

**Comment by tech2serve** [comment]
A reasonable catch. We'll have to look at real estate on the screen.

**Comment by mochel23** [comment]
I made a change on my end to see how it looks and seems to fit:

https://aaflagler.org/meetings/tuesday-morning-silver-dollar-2/

![Screen Shot 2021-05-04 at 4 46 42 PM](https://user-images.githubusercontent.com/69115383/117067804-759ca880-acf8-11eb-95ec-19acae3642aa.png)


I suppose I could add this to the child function in our site but I am not sure if it will create an error.

**Comment by Grateful-Viv** [comment]
This was a great catch @mochel23. 

And these days open and closed have confusing meanings because so many meetings closed (maybe temporarily) due to Covid-19, and then re-opened, even if they're a closed meeting. Ugh, language.

@tech2serve, could you try the following suggestion which shouldn't take too much "real-estate"?

This is an open A.A. meeting which is available to anyone interested in Alcoholics Anonymous.
This is a closed A.A. meeting and is limited to persons who have a desire to stop drinking.

**Comment by Grateful-Viv** [comment]
Thank you for doing this in v3.12
