### ISSUE TITLE
12 Step Meeting List Plug-in Display Issues

### ISSUE THREAD

**Issue by kmryan90** [code4recovery/12-step-meeting-list#331]
The meeting list is presenting with huge letters and not rendering the meeting information when you click on it.  The site was updated to Word Press 5.7.1. As far as I know I did not make any changes.  Will I need to back out this version of WordPress? Has this happened to anyone else?
Link to the site - Vermont AA - http://aavt.org/meetings/

![meeting list](https://user-images.githubusercontent.com/83615246/117093239-60db0780-ad2e-11eb-8518-767acc66fe65.GIF)

**Comment by tech2serve** [comment]
Hi--

First, I assume you're talking about 12 Step Meeting List Plugin so I've edited the title to reflect that.

Second, if the link in your Google drive is an image to show the issue, please post the image here. I don't want to follow links to Google or somewhere else to look at examples.

I have looked at the Vermont AA website and I don't know what is going on. I do know we have a lot of people using Wordpress 5.7.1, so I don't believe that is the issue directly.

What I'm seeing on your site is that it doesn't even appear the `/meetings` url is even being loaded correctly, and you have something like Google Tag Manager loaded?

<img width="501" alt="image" src="https://user-images.githubusercontent.com/31904316/117072370-f1492600-acf5-11eb-8472-cc80ff8ab914.png">

Try disabling that plugin and other plugins to see if your issues resolve.

**Comment by brianw-area24** [comment]
I agree with @tech2serve that I don't think it's WordPress 5.7.1 because a lot of sites are using that version. I did notice that the Vermont AA page is using the Gutenberg plugin. We've had another issue recently where this plugin was updated and the site didn't display properly, so I'm curious if there is something with that plugin that's causing the issue.

If you're comfortable with WordPress, can you try 1 of two things for me:
- Roll back to version 10.5.2 of the Gutenberg plugin
or
- change the file at wp-content/plugins/gutenberg/lib/compact.php. Find the line that says `$load_separate_styles = gutenberg_is_fse_theme();` (line 17) and add this line right after it `$load_separate_styles = gutenberg_supports_block_templates();`

I'm wondering if that changes anything for you. However, only do this if you're comfortable doing so because doing something incorrectly could break your site.

Brian W

**Comment by kmryan90** [comment]
I'll give it a try and let you know.  Thank you for the help.

**Comment by kmryan90** [comment]
I will take a look.  Thank you for the help.

**Comment by kmryan90** [comment]
I deactivated the Gutenberg plugin and my Meeting List was back 👍 
Thank you for all the help.
Vermont AA - http://aavt.org/meetings/

**Comment by brianw-area24** [comment]
Thank you for the followup, glad your meetings page is back.

I'm going to go ahead and close this issue.

Brian W

**Comment by kmryan90** [comment]
Thank you!
