### ISSUE TITLE
12 Step Meeting List (Meeting Time not Working)

### ISSUE THREAD

**Issue by dnosenvid59** [code4recovery/12-step-meeting-list#333]
Been using the 12 Step Meeting plugin for several months without issues.  Since a few days ago, the meeting times are no longer being displayed on our website.  Also, when trying to add a "New" meeting, the "Time" dropdown selector is not populated with anything, it is blank.  Please help!

<img width="880" alt="12 step plugin issue" src="https://user-images.githubusercontent.com/71561731/117371362-5d11c700-ae8d-11eb-89e8-18f4eb506082.PNG">

![image](https://user-images.githubusercontent.com/71561731/117371397-7155c400-ae8d-11eb-98a8-7565aef1976a.png)

Thank  you!
www.greenbayaa.org
District 01 Webmaster

**Comment by tech2serve** [comment]
Hey @dnosenvid59,

Since we haven't updated TSML for a while, please look into what you have changed updated. 

In particular, did you update your theme?
Some other plugin? Try disabling it.
Think through other changes that have occurred, and try rolling them back.

Keep us posted.

**Comment by dnosenvid59** [comment]
I  have not updated my theme.  I'm starting to seriously worry about this.  My only idea is to uninstall the plugin and re-install and re-load the CSV file.  But why can't I even add a new meeting?  There is no way to enter a meeting "time"

**Comment by dnosenvid59** [comment]
<img width="590" alt="Capture" src="https://user-images.githubusercontent.com/71561731/117375493-b4fffc00-ae94-11eb-99b6-41f407d88b8c.PNG">

**Comment by tech2serve** [comment]
In looking in detail at your website elements:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/31904316/117375875-98b08f00-ae95-11eb-87dd-1109387cd8a5.png">


Compare this to my dev site:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/31904316/117376061-ffce4380-ae95-11eb-94bb-acf77dd9c665.png">

So I think your data is quite intact, but something is messing with the display on the front end.

You didn't respond to my question about checking other plugins. I would focus on that before reinstalling the plugin. That may be necessary, but I suggest saving to be more of a last resort.

**Comment by dnosenvid59** [comment]
I update my wordpress plugins quite often.  There have been several that I have updated.  If I could guess one specific change that I made prior to this problem starting is that I added the 12 step meeting plugin to my homepage as a widget.  This could have been the reason for this problem.  I did delete the widget yesterday but the problem is still ongoing.

**Comment by tech2serve** [comment]
Try disabling the other plugins as an experiment. You can reenable them when done.

Do you have the Gutenberg plugin installed? If so, disable it and see if that clears the issue.

**Comment by dnosenvid59** [comment]
I deactivated the plugins and it didn't fix the problem.  (I do not have the Gutenberg plugin)
The widget I added that seemed to cause the problem is the "Upcoming Meetings" widget.  (Removed yesterday)

**Comment by tech2serve** [comment]
I just installed the Astrid theme and didn't see the issue. I run without any other plugins, so it is pretty clean install. 

99% of the time we see an issue like this (and they are pretty rare) it is caused from conflicts with other plugins.  I've never seen an issue caused from the widget. I suspect that was a coincidence.

What version of Wordpress is loaded? Did that update also coincide with the issue?

You can try exporting your meeting list as a csv, then remove and reinstall TSML, and import the csv. If that solves the issue, great!

If it doesn't, you may need to contact your hosting provider to see if they updated anything. In particular, what PHP is the provider using?

Some other @code4recovery/tsml-contributors may be able to provide some other ideas.

**Comment by dnosenvid59** [comment]
I have exported the meeting list csv to begin the re-install process.  However, the meeting "time" is empty except for any meeting with a starting time listed as "Noon"

**Comment by tech2serve** [comment]
Shoot. Well that won't work then. 

However, given that the issue persists across multiple functions and isn't simply display related, I suggest contacting your hosting provider and asking them what has been updated.

**Comment by dnosenvid59** [comment]
Do you think that a restore from an earlier backup by my host provider could fix it?

**Comment by tech2serve** [comment]
It is possible, but I don't know what all the backup includes.

I still suggest coordinating with them first. If you have access to `phpMyAdmin` through your account dashboard, you can explore the database to ensure the data (i.e., meeting times) is there. Given that `noon` shows up, I suspect the data is, and that the issue is being caused by something with PHP's handling of transforming data types (there is no time of "noon" in the database, so the code is transforming that one). Yeah, I guessing here, but I think someone with access to the infrastructure logs and background on what system updates they've made will be of more use to you. 

Do you have access to the file system (`wp-plugins/12-step-meeting-list`) of your account? Or, again, perhaps your hosting provider can help with this: Manually remove and reinstall TSML from the terminal. Doing so doesn't run the code to remove meetings from the database, but would replace all the plugin code with a fresh copy. 

And I'll keep thinking about it and trying to find other potential causes.

**Comment by dnosenvid59** [comment]
Ok.  Thanks very much for all the info.
I really appreciate it!

**Comment by dnosenvid59** [comment]
One other interesting piece of this is that we are connected to the GSO
Meeting Guide app and meeting times are still showing up correctly on the
app. So, the data is still there.

**Comment by dnosenvid59** [comment]
I just did a restore of all files and databases on my website from my host
provider account.
Meeting times are back! :)

**Comment by tech2serve** [comment]
Good to hear!

**Comment by brianw-area24** [comment]
Glad to hear that the restore worked on your site. I was looking at this issue earlier this evening, when everything was happening, and I was able to recreate this issue on my test site, so wanted to post some additional information. TSML uses the "Time Format" from WordPress's settings page. I think some how, this setting got removed from the wp_options table in the Database, or it got changed to a custom value of blank.

![Screen Shot 2021-05-06 at 11 10 07 PM](https://user-images.githubusercontent.com/55821195/117396738-37ea7c00-aec0-11eb-919b-96463abad313.png)

There is really no telling when this may have happened because TSML uses a cache file of the meetings, so it doesn't have to read from the database all the time. It wasn't until this cache file got rebuilt that the time format would have changed on the meeting listing page.

So, if this happens again, the thing we'll want to try is:
1. Go to the WordPress settings page, and change the Time Format
2. Have TSML rebuild it's cache file, either by deleting the file from the wp-content folder, or updating a meeting.

The times for the meetings were in the database all along, just that they weren't displaying correctly. And I think that's because of this Time Format setting.

Brian W.

**Comment by dnosenvid59** [comment]
The meeting times definitely disappeared again shortly after the restore.  I checked my email this afternoon and saw Brian W's post on recreating the issue with time format settings.  I logged in and checked.  He was 100% correct.  Time setting was changed to custom = blank.  I made the change to correct format and meeting times are back as of 2:32 PM CST.  Great catch Brian!  You guys are amazing!  Thank you so much to both **_brianw-area24 & tech2serve_** for helping Green Bay AA fix this issue so quickly.  We owe you all a debt of gratitude.  This tool makes finding a meeting so incredibly easy for our AA members.  Best regards to you both!

<img width="599" alt="TSML Time Settings Issue" src="https://user-images.githubusercontent.com/71561731/117499231-8c354080-af40-11eb-856e-7c5c8e1420eb.PNG">

**Comment by brianw-area24** [comment]
Glad we were able to help you, and that it wasn't something more serious than a setting in WordPress. Also, thank you for your work in getting accurate meeting information available online.

It's an honor to be able to help support this plugin that helps so many people.
