### ISSUE TITLE
Question for WordPress plugin

### ISSUE THREAD

**Issue by GCITechSC** [code4recovery/12-step-meeting-list#340]
Hey all,

I'm a new WordPress user/builder for my intergroup. I just read over the Readme on github and it gave me some better insight. 

My questions remain are I set my own districts and regions for our folks?  If so could I then make one district for online, and another for live meetings?   I've received requests when we put up the new schedule that folks can see those on two separate pages. Is this possible with your plug-in?

Many thanks!
Scott

aacolumbia.org webmaster

**Comment by brianw-area24** [comment]
Thank you for your interest in the TSML plugin.

Yes, you can set your own districts and regions on your site with this plugin. However, most sites simply use city names as the regions, and the AA service structure district for the district. This is especially true if you ever plan on using your site to feed information up the chain, to a District or Area site, or to the Meeting Guide App.

As for seeing in-person and online meetings on two separate pages, that's something that's in the works. Currently, it's easy to show all the online meetings on one page, however, we don't have a good way built in to show in-person meetings. That's the piece we're working on.

You could show in-person meetings by adding a type to the list of types (it says how to do this in the FAQ of the plugin), then giving your in-person meetings this type. However, because this type is defined locally, it won't be used by other sites or by Meeting Guide App.

Brian W.

**Comment by GCITechSC** [comment]
Thanks much for the feedback on this.

**Comment by tech2serve** [comment]
Hey @GCITechSC --

I'm going to close this, but we can reopen it if you have more questions.

Yis, Tim
