### ISSUE TITLE
Adding meeting type codes to 1st page of printed meeting list

### ISSUE THREAD

**Issue by rtillinois** [code4recovery/12-step-meeting-list#342]
My district is using the printed meeting list option. But there is no explanation on the printed list of what the meeting codes (eg. C = Closed XB = wheelchair accessible restroom D = discussion mean. 

So we put them all in the notes for the first meeting that appears on the list, They appear with the bus information, entrance information.

Instead, if the codes could be printed on the top of the first page before the meetings themselves are printed, that would be more helpful for newcomers not familiar with AA meeting formats.*Is your feature request related to a problem? Please describe.**

This app has been so wonderful for our district during COVID,!  Thanks for all your work!

**Comment by tech2serve** [comment]
Thank you for the suggestion. Yeah, our printed PDF is very basic, and has not gotten much love.

Another developer has created 12 Step Meeting PDF Generator. I have not used it a lot, but it does allow for the admin to add additional HTML at the top of the page that *could* include a legend for the meeting types. You might want to check that out.

**Comment by mousehelp** [comment]
I've been asked to add meeting types to the list of selectable meeting types available to people who create meetings. Would this be considered a request for a new feature/enhancement to the plugin? Thank you.

**Comment by joshreisner** [comment]
@mousehelp thanks! are you asking about the printed PDF meeting list? or adding meeting types in general?

**Comment by mousehelp** [comment]
Sorry for the lack of specifics. Yes, I need to add more types to the meetings people can create. Iff I am on the wrong thread, please redirect? thank you.

**Comment by joshreisner** [comment]
ok yeah, this thread is about listing the meeting types in the PDF.

the global list of meeting types (for AA meetings) come from the authoritative list here: https://github.com/code4recovery/spec#meeting-types

in all likelihood, what you want to do is add a custom meeting type to your local website, please see this FAQ item: https://wordpress.org/plugins/12-step-meeting-list/#my%20meeting%20type%20isn%27t%20listed%21

the code for that goes in your theme's functions.php code

**Comment by mousehelp** [comment]
cool. Thanks!

**Comment by joshreisner** [comment]
just noting the original request above (printing a legend of codes on the first page) has been implemented now in the PDF project, here is an example: [directory.pdf](https://github.com/code4recovery/12-step-meeting-list/files/7875359/directory.pdf)
 
* go to meetings > import & settings
* make sure 'sharing' is set to 'open'
* click 'generate pdf'
* check 'meeting types legend'
* 'generate pdf'

going to close this issue because i think the old PDF generator in TSML is no longer being developed.

@mousehelp if you encounter any issues with the new one, please let us know over at [https://github.com/code4recovery/pdf/issues](https://github.com/code4recovery/pdf/issues), thanks
