### ISSUE TITLE
Update to 3.10.0 from 3.1.13

### ISSUE THREAD

**Issue by rstelma** [code4recovery/12-step-meeting-list#346]
Thank you for your reply.

I have a site that has version 3.1.13. There isn't a prompt to "update now". How can I update to 3.10.0? I'm concerned about losing data if I "deactivate" and/or delete.

![NOcentralOffice](https://user-images.githubusercontent.com/68346976/119021569-319adc00-b965-11eb-8ad0-520bf8d13b28.png)

Thank you,
Richard

**Comment by tech2serve** [comment]
Hi @rstelma/Richard--

This is a great question, and one that I'm not sure I have the ability or bandwidth to test out ahead of time. I am a bit surprised you don't have an update now button but it may be because of the organization name change? ::shrugs:: 

Since you're updating from such an old version, I strongly suggest you make multiple backup copies of your data before doing anything. This can be done through whole site backups to be sure (outside of the scope of our Code for Recovery issues page) and by exporting your database to a CSV (Meetings -> Import & Settings -> "...download your meetings...") file:

![image](https://user-images.githubusercontent.com/31904316/119068719-5d8c8080-b9aa-11eb-97ed-4104d65bbf2c.png)

The `Deactivate` button _**should not**_ delete any data, but if you explicitly click "Delete" the plugin **will delete your data**. So, don't click delete unless the steps below don't work. To be safe, I would be prepared to be required to import a new database from your csv file. 

![image](https://user-images.githubusercontent.com/31904316/119069512-e1933800-b9ab-11eb-95af-39c6c6febad1.png)


With backups in place, I am hopeful you can simply deactivate the plugin, and then install 12 Step Meeting List over it (Plugins->Add New) and the necessary database and code changes should apply. We have not changed the folder in which the plugin resides, so unless you (or a previous admin) did on your site, I think the installer will just overwrite the older version.

Again, please make sure you have good backups in place.

Please keep us posted on how this goes for you.

**Comment by rstelma** [comment]
Hi,

Thank you for your reply.

Exporting to "CSV format" just gives me a blank CSV file. No help there.

I have a good backup of the website.

Can you tell me what the SQL query is for the CSV export so I can run that directly against the database?

I'd like to get the meeting data before I try anything.

Thanks,
Richard

**Comment by rstelma** [comment]
Where did you see the organization name change?

**Comment by rstelma** [comment]
Another strange thing about this site, it's pulling data from another district but when I look at the data sources by clicking "right here", nothing comes up.

I copied the meeting listings from a browser and put it into an excel file and cleaned the data separating the weekdays from the times. The only thing is that it includes data from another district. I could probably clean that up too by filtering out the cities that are not in the district of this website.

Website I'm working on - aaneworleans.org
Has data from - district12.org

**Comment by tech2serve** [comment]
Hey @rstelma,

Regrettably, it isn't as simple as my giving you the sql command as Wordpress (and the plugin) puts information in three different tables, so data is transformed prior to export.

I am noticing a number of errors on your site, which may be interfering with the export to csv. I do notice that the front end javascript isn't working right when I change a filter. 

![image](https://user-images.githubusercontent.com/31904316/119242359-b8e17e80-bb22-11eb-9955-5478cef7cc4d.png)

What version of Wordpress is your site using? And which version of PHP does your hosting platform have installed?

You might try disabling plugins (other than TSML) and see if the export process works.

Do you have access the file system for your site?

**Comment by rstelma** [comment]
Another strange thing about this site, it's pulling data from another district but when I look at the data sources by clicking "right here", nothing comes up.

I copied the meeting listings from a browser and put it into an excel file and cleaned the data separating the weekdays from the times. The only thing is that it includes data from another district. I could probably clean that up too by filtering out the cities that are not in the district of this website.

Website I'm working on - aaneworleans.org
Has data from - district12.org

**Comment by rstelma** [comment]
Hi,
Thank you.

Wordpress Version 5.7.2
PHP Version 7.3

I followed your suggestion to disable plugins and I noticed there was actually a plugin called "Disable Updates". I deactivated that and it gave me The Meeting List update link. I updated. Tried the CSV export. Got a file with no data.

Now I'm also seeing updates available for all the other plugins.

There are a few more plugins I could try deactivating. 

I still would like to pursue writing a query to retrieve the data. Any help you could offer would be greatly appreciated.

A couple of years ago I was in touch with Josh. I was asking him about a query to get the data and he wrote:
*******************************************************************
Because the plugin follows WordPress conventions and uses its native schema, fetching the data out in a single query would be a challenge. You could write a PHP script adapting the code in tsml_get_meetings() (located at includes/functions.php). I’d be interested to see what you come up with.

Your basic query is something like

SELECT
p.id,
p.post_title name,
p.post_content notes,
l.id location_id,
l.post_title location,
l.post_content location_notes
FROM wp_posts p
JOIN wp_posts l ON post_parent = l.id
WHERE p.post_type = “tsml_meeting" AND p.post_status = “publish"

Then you build on that by fetching everything with that id and location_id out of wp_postmeta, that’ll give you the address, day, time, etc.

Then you build on that by fetching terms out of the wp_terms / taxonomy tables to get the region (using the location_id).

Then groups, if you get that far lmk and I can tell you how to get those…

Good luck! If it’s useful I’ll be pleased to let other groups know about it.
***************************************************************
I get nothing back from that query of course, especially since he wrote that it was "something like".

I don't have an appearance editor now either, possibly another plugin blocking that functionality.

Anyway, I'm having trouble finding tsml_get_meetings(). Can you tell me where that is and how I can get to it?

Thank you very much.

Richard

**Comment by tech2serve** [comment]
`tsml_get_meetings` is defined in `functions.php` around line 1038 (depending on which version you're running).

When you said the update worked, does that mean you're running TSML 3.10?

I have noticed now with your site there are still a number of errors showing in the console, and I suspect they're being caused by other plugins. The good news is that I can now change filter parameters on your meeting list page, and it works! That is progress.

TBH, if you've gotten this far, I suggest we figure out why the exporter on your site is not working. For starters, continue to disable and update the other plugins. I will say another plugin conflicting is *probably* the cause of your issue. Once you've disabled the other plugins, please open a debugging console and watch for errors while you run the export to csv function. Post those errors here, please.

**Comment by tech2serve** [comment]
Can re-open if OP returns.
