### ISSUE TITLE
Map as default view

### ISSUE THREAD

**Issue by jmh2911** [code4recovery/12-step-meeting-list#360]
Hello,

Is it possible to have the map as a default view instead of the list?

If so, is it also possible to zoom in by location of the user?

Thanks!

**Comment by tech2serve** [comment]
Sure. Modify the link used for the meeting listing in your menu entry and add `&tsml-view=map`.

The zoom level should be automatically set to encompass all the meetings in the list. The plugin does not request the user's location.

**Comment by jmh2911** [comment]
That would make sense right and that was the first thing I tried. It doesn't work. It auto reverts to list view. https://liferecoverygroups.com/ click on groups.

**Comment by joshreisner** [comment]
the issue here is it looks like you've been using the plugin a long time, and you've got a legacy url structure, because your groups link is to https://liferecoverygroups.com/meetings/?d=any&v=list&tsml-view=map

the "v" param was renamed to "tsml-view" a few years ago, so those two are in conflict. this link should work for you

https://liferecoverygroups.com/meetings/?tsml-day=any&tsml-view=map

**Comment by jmh2911** [comment]
oh - excellent - thank you so much!
