### ISSUE TITLE
Where do I properly write the PHP? 

### ISSUE THREAD

**Issue by GCITechSC** [code4recovery/12-step-meeting-list#373]
Hey all,  I've taken your suggestion and joined TIAA for some other things.

One thing I'm trying to accomplish is getting into the Functions PHP and write the proper thing in the proper place.  Our intergroup website is aacolumbia.org  and I've been asked to get the meeting list to be sortable by meeting name and discontinue sorting by address.  So we'd like to be able to sort by time, name, location, and region.  I've seen the other places where you describe how to do this, but again, I'm new to this part of website management and would appreciate some guidance and help.  

Here is a screenshot of what I think is the right place to go to do what you say, but then where within this PHP (what line) do I write down the proper stuff for $tsml editing?  Thanks in advance.

Scott

![image](https://user-images.githubusercontent.com/84104513/122447896-35287f80-cf72-11eb-997b-51635f485109.png)

**Comment by tech2serve** [comment]
Scott,

Let me start by saying thank you for your patience with us (and me in particular). My response to all this has been slow, and not particularly helpful both here and on TIAA Forums.

Part of the challenge here is that you’re asking some Wordpress development questions that are technically not specific to TSML. In these cases, we generally encourage users to seek out alternate sources of help and information. I realize sometimes those sources will point back to the plugin, and so it gets frustrating for users in situations similar to yours.

It is not advisable to directly edit the plugin’s `functions.php` (or any other files in the plugin folder) because any update we send out will overwrite your changes.  

If you want to hack on TSML (which we welcome users to do) you have two general options. The first is to fork the code to your own repo following the steps outlined in our [README documentation](https://github.com/code4recovery/12-step-meeting-list#helping-with-development). Using this approach, you change the plugin as you wish and then deploy that version to your site. If you think your changes and improvements warrant inclusion in the official plugin, you can do a pull request and we’ll evaluate the proposed change. 

The advantage of this approach is that you have full control of the code from that point forward, but you can also incorporate our changes to keep your code current. The disadvantage is that this can be a lot of work for you to keep these versions in sync. And this you really should do!

The second approach is to add what is called a child theme (use your favorite search engine to learn about this) that then allows you to write your own code and include it, thus overriding the original code. I have personally used this approach for minor changes, in particular custom styling. The primary advantage of this approach is that you continue to update the plugin as we make changes, and you’re simply responsible to maintaining your own code in the child theme.

A little later today I’ll be diving into our code base for some other work, and I’ll try to pay attention to where the sorting is done in order to give you a better pointer.

**Comment by tech2serve** [comment]
Hey @GCITechSC,

As stated above and on TIAA Forum, creating a child theme is the way to go. 

As a webmaster of a Wordpress site, this is a common requirement. Internet searching will provide step-by-step directions. This is a Wordpress thing, and not a TSML requirement…we simply leverage the feature in Wordpress to allow users to make customizations. 

Any plugin or theme a webmaster wants to modify the behavior of should be done through creation of a child theme, and along with that a `functions.php` file that augments the multiple other `functions.php` files. Generally, every theme, every child theme, and every plugin has a `functions.php` file that works together with the others inside Wordpress.

A child theme is the method Wordpress uses to augment existing themes and plugins. If you have theme “cool-theme” activated on your site, then you create (using the steps you find in a tutorial) a child theme called “cool-theme-child” and once you have the desired customization, you activate the “cool-theme-child” and that then augments “cool-theme”. While I appreciate you apprehension, it isn’t generally anything to be afraid of because if you have an error in the child theme, you simply reactivate the original “cool-theme”, make the necessary corrections and try again. 

It is always a good idea to have a backup before you do significant changes. You also might want to spend the money and get a staging/dev/test Wordpress site to learn on.

Good luck!
