### ISSUE TITLE
Refresh browser before city changes

### ISSUE THREAD

**Issue by wlewis1055** [code4recovery/12-step-meeting-list#384]
When I select a different city from my dropdown, often the city doesn't change and I have to refresh the browser before the city changes.  https://arkansascentraloffice.org/meetings/
Wilma

**Comment by tech2serve** [comment]
When we’ve seen this type of situation in the past, it is due to something interfering with the plugin (specially, the JavaScript).

Please look in a browser debug console for any errors that occur. 

Disable all other plugins and then start turning them back on one at a time. When the situation returns, you’ll know which one is causing the problem.

**Comment by joshreisner** [comment]
It's working for me in Safari on mac. 

One issue that I do see is that regions seem to be listed twice, with themselves as their own parent. Are you importing from CSV? 

![Screen Shot 2021-06-25 at 9 41 11 AM](https://user-images.githubusercontent.com/1551689/123458234-a92ddd80-d599-11eb-8eab-26738bd383cb.png)

I wonder if there are issues with region and sub-region in the CSV that are causing this.
