### ISSUE TITLE
Version: 3.11.0 Issue with "Active" filtering persistence and URL

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#396]
1. Is it possible to not dim on list view, the Location/Group text if the meeting is active and online? Could you just dim it for inactive meetings?
2. Is it possible to not dim on list view the Region data if the meeting is active and online? Could you just dim it for inactive meetings?
2. Is it possible to have the default be active meetings? I know I can set it up to open as `/meetings/?tsml-day=any&tsml-attendance_option=active`, but when I select back to meeting after viewing a meeting, it reverts back to any type.
3. Would it be possible to leave /women or /men or /online meeting the way it was? That was after the meeting name, in bold green font. It doesn't improve anything to have, for example, (women) on the next line, when the current version shows it in the same line and stands out since it is green color and bold. From our perspective, particularly if it's a men's or women's meeting, it really needs to stand out better and the previous version (3.10.0)  was just fine.

![Old Tuesday 6-7](https://user-images.githubusercontent.com/62247421/123831114-fb406d00-d8d1-11eb-92a5-b7fcd47aeb06.png)

![New Tuesday 6-7](https://user-images.githubusercontent.com/62247421/123831144-04c9d500-d8d2-11eb-8c80-4c17a626b456.png)

Some of these same comments were made on #377 

Thanks.

**Comment by tech2serve** [comment]
> 1. Is it possible to not dim on list view, the Location/Group text if the meeting is active and online? Could you just dim it for inactive meetings?
> 2. Is it possible to not dim on list view the Region data if the meeting is active and online? Could you just dim it for inactive meetings?

We’ll always discuss and evaluate our UX, but for now you’ll be better off using CSS on your site to change these to how you want them.

> 3. Is it possible to have the default be active meetings? I know I can set it up to open as `/meetings/?tsml-day=any&tsml-attendance_option=active`, but when I select back to meeting after viewing a meeting, it reverts back to any type.

This was discussed extensively amongst our developers and we decided the current approach is best. We do not intend to change the behavior for the time-being. 

I do understand the switch to showing all can be unexpected behavior, so we’ll look at this closer in the future. 

> 4. Would it be possible to leave /women or /men or /online meeting the way it was? That was after the meeting name, in bold green font. It doesn't improve anything to have, for example, (women) on the next line, when the current version shows it in the same line and stands out since it is green color and bold. From our perspective, particularly if it's a men's or women's meeting, it really needs to stand out better and the previous version (3.10.0)  was just fine.
> 

This was also discussed extensively, and we decided the current approach is more aligned with where we’re going with the UX. Again, this is something you can explore tweaking with CSS on your site.

**Comment by joshreisner** [comment]
> when I select back to meeting after viewing a meeting, it reverts back to any type

☝️ this looks like it could be a bug. i'm noticing that when you navigate to a meetings page the `attendance_option` parameter is lost

**Comment by Grateful-Viv** [comment]
>We’ll always discuss and evaluate our UX, but for now you’ll be better off using CSS on your site to change these to how you want them.

Can you point me in the right direction of what is the CSS to use on my site that won't dim Location/Group & Region text if the meeting is active and online?

>This was also discussed extensively, and we decided the current approach is more aligned with where we’re going with the UX. Again, this is something you can explore tweaking with CSS on your site.

Not sure where you're going with with the UX, but can you give me a clue what the CSS would be to revert back to  /women or /men or /online meeting the way it is in v3.1.10?

**Comment by OSAwebsite** [comment]
Two questions about the new version:

Q1 I do not notice having the option to include the new 'yes/no' active options in the import template. When is that coming?

Q2 On my staging site I see that some meetings that are just online, now show up with "in person and online"; how did the update come to that (incorrect) conclusion?

I would appreciate what Viv is asking for: a central place where we can all go when needing CSS without being proficient in that language.

Please keep in mind that the update will trigger a truckload of work for large areas with hundreds of meetings, if we have to check them one by one for possibly incorrect tags. That is where the import option comes in: please include the new settings in that template so that we can choose to do a total refresh by importing from a non-Wordpress database source.

Congratulations on yet another new version and thank you for your ongoing hard work!


Nicky

**Comment by tech2serve** [comment]
Hi Nicky,

>Q1 I do not notice having the option to include the new 'yes/no' active options in the import template. When is that coming?

I'm glad you brought this up  In your spreadsheet, any meeting that has a specific address and doesn't have the TC type *should* be treated by the plugin as satisfying the requirement for "in-person".

Additionally, if the meeting entry has a valid online Conference URL or phone, the meeting can be attended "online".

So if you're importing a meeting that you intend to be available online only, make sure to leave the address as approximate (i.e., city and state only), unless it is an online meeting in lieu of a location that is temporarily inactive/closed. In that case, you should include the TC in the types for the importer to assign it correctly.

>Q2 On my staging site I see that some meetings that are just online, now show up with "in person and online"; how did the update come to that (incorrect) conclusion?

Probably because you have a specific address in for the meeting and the TC type isn't present. Or, if it is, we may have a bug. 

These are two really good questions. If you're finding the clarification isn't sufficient, or you're still seeing incorrect behavior, please let me know and I can (or you can I think) use your comment above to open a new issue (but report).

As far as custom CSS work, that is beyond our scope. There are plenty of sources that can be found for Wordpress plugin/theme customizations. DuckDuckGo or Google is the best place to start along with any tutorials that talk about how to inspect a website and determine which CSS is being used to display an element.

**Comment by tech2serve** [comment]
I've confirmed something is finicky with the "active" filter. I can usually get it to work the first time using the drop down, but I'm also often having trouble getting it to work as a URL.

**Comment by OSAwebsite** [comment]
Chiming in here with regards to the hiding/showing of addresses for inactive meetings in the main list of the plugin.

I get quite a lot of feedback from newcomers/coming-backers that tell me that, although they like the option of Zooming around the world, they also want to know if there are local meetings. They want to see where they are held and they want this because, once the world opens up again, they know where to go in within their own geography. For that reason I prefer graying out over omitting. And I do not like how empty the details page is when the plugin opts to omit the address, I'd rather show everything but signal in a different way that a meeting is inactive. Graying out works find for me.

It will be hard enough to re-open doors for groups that currently only are in touch by phone and email with their core members. It would be good to keep their details out therre. Or, alternatively, find a way to have a toggle that says: show or not show a meeting. I know that we can play with the draft status or the private status so that it does not show up, but do keep in mind that some of us have a substantial list of meetings to maintain and doing that just within Wordpress takes a lot of work. Anything we can hammer in as a permanent checkbox choice would be a more efficient option.

**Comment by OSAwebsite** [comment]
I have checked out the content of the meeting that shows up as 'online' and 'in person' and cannot find anything that would trigger that tag. It has the general Zoom page as URL, and in the details it says:
"Participation in the online meeting is managed through the Telephone Answering Service at phone number ###-###-3333"

The general URL is to ensure that the button remains clickable even though the posting does not show Zoom credentials. Maybe that is the trigger but that would be a bit weird.

All of my meetings show a geographical address, by the way, see previous post for the reasoning behind that.

It would be good to give us options to set in new versions, rather than make choices for us. The more flexibility the better. The checkboxes for meeting specifications seem to be the most logical place. If there were a box with 'hybrid' or a box for both 'on-line' and 'in-person' and even one with 'outdoor' and 'indoor', as admin we are in full control of which tags will show up in the webpage. I think sometimes during software development too much automation is introduced.

Btw, would love to be a part of your UX team....

**Comment by tech2serve** [comment]
> I have checked out the content of the meeting that shows up as 'online' and 'in person' and cannot find anything that would trigger that tag. It has the general Zoom page as URL, and in the details it says:
> "Participation in the online meeting is managed through the Telephone Answering Service at phone number ###-###-3333"
> 
> The general URL is to ensure that the button remains clickable even though the posting does not show Zoom credentials. Maybe that is the trigger but that would be a bit weird.
> 
> All of my meetings show a geographical address, by the way, see previous post for the reasoning behind that.

We need to maintain compliance with the Meeting Guide API, and this spec interprets a meeting with a specific address as meeting in person unless the TC type is included. The latest version of the plugin handles this for the user.

Please give me the link to the specific meeting in question, and what part of the data is not correct.

**Comment by OSAwebsite** [comment]
I don't think it would do you much good to see all details in any of my meetings, to be honest, for the simple reason that there is apparenly a logic in the coding that makes a decision that leads to the displayed tags. It is no different from the following meeting on the live site:
http://al-anon.alateen.on.ca/meetings/elec-faith-hope-serenity-afg-orillia-d1/?tsml-day=any&tsml-district=district-1

Nowhere in that listing is the term 'in person'. There is just the term 'online' in the Meeting Information section. It does have an address, but so does 99% of the other meetings and they do not show that tag.

When you look at the TSML logic, it should tell you where the incorrect double tag comes from. Like:

If (term found = "in person" ; apply tag "in person").

I migth be making this simpler than it is in your code, but if you find what triggers the tag, the all admins can make sure that their meetings have the correct tag.

**Comment by OSAwebsite** [comment]
Here is food for thought:
I did not just find this one meeting with this phenomenon, but several more. No idea what triggers it. Most of them have different physical locations but as mentioned before: it is important to keep that info visible. Or at least as admin have influence on whether it is displayed or not.

When I was going back and forth between details page and list page I did see that there is indeed something wonky with going back to the most recent selection (day, region, district filters). Also, the manual search option does not seem to be functioning. It does nothing. Searching by District does work.

Good luck with the de-bug!

**Comment by OSAwebsite** [comment]
Just another thought:
There was an earlier plugin version that did its own thinking about when to show the trigger 'online' or not. I seem to remember that it depended on having a valid URL in place.
If the checkbox for 'temporarily closed' was ticked, then that tag would show up.
It might be that the cause of the current inconsistencies can be found in that piece of the code.
Maybe it makes a decision that was valid at the time, but when built upon with additional code can not longer correctly decide the tags. Idea?

**Comment by OSAwebsite** [comment]
Sorry for another separate comment, my mind is a bit inefficient, it seems.

When the automatic 'online' tag was introduced, it went hand in hand with the strike through and later greying out of the location address. So that might also be a part of the code to look at.

**Comment by joshreisner** [comment]
Hi @OSAwebsite sorry that the logic isn't clear. The reason your meetings are showing up as In-Person (in addition to online) is that they have street addresses and were not labeled as "Location Temporarily Closed."

http://al-anon.alateen.on.ca/meetings/elec-faith-hope-serenity-afg-orillia-d1/?tsml-day=any&tsml-district=district-1

> All of my meetings show a geographical address, by the way, see previous post for the reasoning behind that.

I didn't see the previous post, but for those meetings that are "natively online" we generally don't advise using a fake street address for them, because that could cause confusion. Instead we advise you to use an approximate address, like Orillia, ON. This will help in a number of ways: it will hide the pin on the meeting listing, it will hide the "Get Directions" button, and it will hide the street address.

If on the other hand this is an in-person meeting that has "temporarily moved online" then the suggested course (prior to this update) was to use the "Location Temporarily Closed" tag. After this update it's to mark "Can I currently attend this meeting in person?" with "no." This will keep the pin on the map, but will cross out the address and hide the Get Directions button.

Hope that helps a little to clear up the confusion.

**Comment by Grateful-Viv** [comment]
This thread has morphed into other issues that are not addressing what I opened the ticket for. 

I am attempting to address numbers 1, 2 & 4 in the original thread above with CSS. But there's still the active filter dropping issue that is being addressed. For now, have only installed v 3.11.0 on my staging site.

There are other issues as well, but I will open another ticket (I assume that's what these are).

**Comment by joshreisner** [comment]
@Grateful-Viv I agree. Let's keep this thread focused on the Active filter. 

@OSAwebsite if you want to discuss the auto-tagging of entries as Online and In-person, please open a new issue.

Thanks

**Comment by OSAwebsite** [comment]
I have entered a bug report about the auto tagging.

**Comment by Grateful-Viv** [comment]
I have figured out most of the CSS for numbers 1, 2 & 4 above. It may be a kluge, but it's the best I can do for now.

However am holding off on updating plugin on the live site until the active filtering is resolved. Any idea of the time-frame for that? Not nudging you all, just trying to get a head's up. Thanks.

**Comment by Grateful-Viv** [comment]
Confirming that the URL ` /meetings/?tsml-day=any&tsml-attendance_option=active` does not open active meetings. 

On the other hand, `/meetings/?tsml-day=any&tsml-attendance_option=in_person` does open all in-person meetings, as does `/meetings/?tsml-day=any&tsml-attendance_option=online` open online meetings.

**Comment by tech2serve** [comment]
Yes. And I believe `/meetings/?tsml-day=any&tsml-attendance_option=inactive` works the first time.

Active filtering from the dropdown seems to work, but I'm pretty sure we have a but in our URL parsing.

Hoping to get to this next.

**Comment by Grateful-Viv** [comment]
Is this resolved?

**Comment by Grateful-Viv** [comment]
Updated plugin and this all appears to be working well. Nice work!! Thank you.
