### ISSUE TITLE
Upcoming Active Meetings

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#398]
This could be a feature or a bug. Putting it here.

When people go to the website to find a meeting, they want to see upcoming meetings (and only active ones). This issue is different from #396.  

@joshreisner setup the UI version to show all the meetings for the week, starting from the time zone the user views it. That would be ideal since we'd no longer run into no meetings to display if it's late in the evening.

I don't know if you work on the WordPress TSML Widgets, but the Upcoming Meeting Widget would be great if there was a way to filter out inactive meetings and work in a similar fashion. It does give you the capability to select how many meetings you want to have displayed.

Thanks.

**Comment by tech2serve** [comment]
I’m adding the new feature/enhancement label, but not yet adding it to our project board until our group has a chance to discuss this.

I’m curious, how are you validating that the meetings you have as inactive are indeed still viable (meaning group/organizers truly intend to restart it sometime soon). I ask this because I’m hearing from an increasing number of admins that they are removing TC meetings(**) from their list unless they have confirmation they will reopen soon. 

**By removing, they may be simply putting the meeting in draft status.

**Comment by Grateful-Viv** [comment]
I’ve considered putting all inactive meetings in draft mode. Was holding off until the new release which would I thought would let us hide the inactive ones by default, but still give an option to view them. A few are slowly coming back. We had one just two days ago. 

But it’s appearing that it would make the whole thing much easier and cleaner if they didn’t even show up. It’s been over a year most of these meetings have been suspended, so I believe it’s way past time. And yes, not delete them, but put them in draft mode. We already do this for seasonal beach meetings that end after the summer. 

And in that case, there wouldn’t be much incentive to update the plug-in on our end to v3.11.0 other than easily select in-person indoors, outside and online, which was already set up by having menu options. 

For in-person indoors, made a note with word indoors somewhere in the text and created this menu item:` /meetings/?tsml-day=any&tsml-query=indoor`

For online, it was easier `/meetings/?tsml-day=any&tsml-type=ONL` and outdoors was `/meetings/?tsml-day=any&tsml-type=OUT`
