### ISSUE TITLE
Bulk updating each city with proper districts

### ISSUE THREAD

**Issue by CathyN-Oklahoma** [code4recovery/12-step-meeting-list#403]
I'm not an expert at anything, but have searched all the forums for help on Bulk Updates.  We've just added Districts and I need to update all of each town's meeting with appropriate district.  Can I do this on Bulk Update?  Or is there another option?  As far I can tell Bulk updates are very limited.  Help would be appreciated.  Post here or notify me on admin@okcintergroup.org
I'm in Oklahoma City and am the Intergroup Manager.  I also wear the "tech support" hat but that is laughable.  Thanks.

**Comment by tech2serve** [comment]
We do not provide a direct way to bulk update districts. 

The best workaround (since this is a one time task you’re working on) is to export your meeting database to a csv file, add district data to that file for the meetings in question, and then reimport the database from the csv file.

It would be best if you have a test/demo site to practice this on. In either case, make sure you have backups of any data you’re not willing to lose.

Good luck!
