### ISSUE TITLE
Version 3.11.0: Display of meeting address

### ISSUE THREAD

**Issue by OSAwebsite** [code4recovery/12-step-meeting-list#406]
I would like to ask that the omitting of a meeting address when a meeting is online is reverted back to the previous version.
I find that many newcomers are fine with attending a random Zoom meeting, but they also almost always want to see if and if so where meetings are held in their neighbourhood when the world goes back to normal face-to-face meetings.

The new version omits the address in meetings that are online and the details page looks like there has been an error because of it. It does not show the address or the map, and because there is an issue with the tagging of meetings (online or in person or both), the address sometimes shows and sometimes not. Please go back to graying out and strike-through. That is a more intuitive solution: newcomers understand that a meeting is not currently held at the address, but they can see where it is for future reference.

Until this is fixed, I cannot upgrade my life site to this newer version...

Thanks for your consideration,
Nicky

**Comment by Grateful-Viv** [comment]
I am trying to follow your logic and entered a new meeting. First with a real address and it published fine. By default it was checked yes, for meeting in-person. Then I selected "no" and it reverted to Temporarily Inactive, with the map hidden and the street address was crossed out. Then I entered a URL and it reverted to online, with the only change being the label "online" in the meeting detail. The address was still there (and crossed out). Finally, I selected "yes", it meets in-person and online (aka hybrid) and the map is displayed.

**Comment by tech2serve** [comment]
> I am trying to follow your logic and entered a new meeting. First with a real address and it published fine. By default it was checked yes, for meeting in-person. Then I selected "no" and it reverted to Temporarily Inactive, with the map hidden and the street address was crossed out. Then I entered a URL and it reverted to online, with the only change being the label "online" in the meeting detail. The address was still there (and crossed out). Finally, I selected "yes", it meets in-person and online (aka hybrid) and the map is displayed.

If I followed this, and I think I did, what you’ve described is the correct behavior.

See the logic described in my comment to #405. 

We don’t want to present normally displayed addresses if a user cannot attend that particular meeting in person on this day. 

If a meeting can be attended online, there are three additional situations that may be true for the user:

1. They also can attend the meeting in person (thus making it *hybrid*). If so, the admin needs to make sure the answer provided for “Can I attend in person?” is *yes* and that a specific address is provided (so the user knows how to get there). The address information should be shown to the user.
2. They previously were attending the meeting in person, but now cannot because the meeting location is temporarily not available. After entering the online information, the admin should check *no* to attendance question. The address information (previously entered and non-approximate) should not be shown to the user since they cannot go to the meeting in person this day. The address does still show on the single meeting page for reference, but is lined out.
3. The meeting is natively online (i.e., never available to the user in person). For these meetings, an approximate address remains required because we associate the meeting to the geographical area and it provides the necessary time zone for users.

If the logic I’ve been describing here is not what your’e seeing, please provide specific data and screen shots.
