### ISSUE TITLE
Gray out past meetings in today's list

### ISSUE THREAD

**Issue by tech2serve** [code4recovery/12-step-meeting-list#41]
An [enhancement was requested](https://wordpress.org/support/topic/shortcode-for-going-to-meeting-page/) in the support forums for the plugin to gray out meetings that have already occurred (started? Ended? Half way through?).

**Comment by joshreisner** [comment]
Let's not actually fade the meetings for everyone by default, but instead let's add a class like `past` to the rows so that Southern Delaware could fade theirs with CSS.

**Comment by tech2serve** [comment]
I think we need to discuss this as it relates to #107 and Milestone TSML v4.0. With @code4recovery/tsml-ui, should the default behavior be to only show future and in progress meetings? All meetings for the day, but with the option to gray them out?

@code4recovery/tsml-contributors

**Comment by 97eighty** [comment]
Hey @joshreisner. How about adding tsml_past class to tsml_ui?

**Comment by joshreisner** [comment]
@97eighty graying works well in Meeting Guide because of the way scrolling works; those meetings are above / outside the main viewport. If you scroll up you need an indication that those meetings are not available, and it creates a demarcation so you know where "now" is when you scroll back down.

TSML might benefit from it, since in the default view you are typically seeing a bunch of old meetings.

But TSML UI handles past meetings by putting them at the end of the list, so it's a pretty different use-case than both of those. I don't think it will make sense for a user if they scroll all the way down past six full days of upcoming meetings and get to a patch of grayed out ones.

It's not a lot of work to add a class, but I'm not sure it's something that anyone would ever request in TSML UI.

**Comment by joshreisner** [comment]
@97eighty oops i forgot about this use-case https://aasantacruz.org/?weekday=6

i guess it could be helpful when weekday is selected and is today. would you want to gray out past meetings there?

**Comment by 97eighty** [comment]
@joshreisner I'm fond of the current color scheme but others may want to change.
