### ISSUE TITLE
Meeting Body Location Address Display Online (TC) v Online 

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#411]
For online meetings with TC type, in v3.10.0, the address was dark grey and text-decoration: line-through. 

For online meetings without TC type, in v3.10.0, the address was black and no strike-through.

However, in v3.11.0, both inactive and online are the same which is strike-through. This should not be the case for online that never met at a location. I would like to modify the CSS so that these kind of meetings do not have the address with a strike-through.

Are you no longer making a distinction between online and TC type meetings to just online meetings?

**Comment by tech2serve** [comment]
You should feel free to modify it as you see fit for your site. 

If a meeting cannot be attended in-person, then I believe any specific address should be lined out. We don’t want to accidentally send a person to an address that is simply there because a meeting is temporarily inactive.

We’ll continue to evaluate how we can simplify the UI. Less is more.
