### ISSUE TITLE
Add method for custom/overrideable Import formatting 

### ISSUE THREAD

**Issue by kiyote33** [code4recovery/12-step-meeting-list#439]
**Is your feature request related to a problem? **
Need to modify data source records from regional central offices to align with format used by area website. For example, some regional central office websites use sub-regions like 'NorthEast', 'SouthEast', etc. which need to be stripped out as they are meaningless when imported into the area website.

**Describe the solution you'd like**
1 - Create empty function 'tsml_import_reformat' which receives/returns meetings array. Make it overrideable by adding "if (!function_exists('tsml_import_reformat')) before its declaration and give it an action filter so the function can be intercepted and modified from a child theme.
2 - Modify function 'tsml_import_buffer_set' to always pass meetings array through tsml_import_reformat. 

**Describe alternatives you've considered**
Modify functions.php directly, which would of course always get over-written on every version update. 
Or...
1 - Rename function 'tsml_import_reformat_googlesheet' to simply 'tsml_import_reformat',
2 - Add global variable $tsml_domain_identifier with a default  value (i.e. tsml_domain_identifier = 'spreadsheets.google.com') to variables.php, 
3 - Make tsml_import_reformat function overrideable by adding "if (!function_exists('tsml_import_reformat')) before its declaration,
4 - Modify function 'tsml_import_buffer_set' to call tsml_import_reformat instead of tsml_import_reformat_googlesheet, and use the new global variable $tsml_domain_identifier instead of the hard-coded "spreadsheets.google.com". 
5 - Add an action filter for the function so it can be intercepted and modified by the area website code from a child theme.

This is starting to violate the KISS principle. So am going with the top level thoughts...

**Additional context**

**Comment by joshreisner** [comment]
This exact function check [already exists for CSV importing](https://github.com/code4recovery/12-step-meeting-list/blob/2f8f64a517d5eac545bb5d64bed6fa01102019fe/includes/admin_import.php#L58-L61) so this request should be pretty easy; just move this functionality into `tsml_import_buffer_set` so that it's shared with CSV importing

Creating an empty function should not be necessary. Also don't worry about the overlap with Google sheets, just call it after `tsml_import_reformat_googlesheet`. That way if a Google sheet data needs to be reformatted in some way when it's imported it can do that.

**Comment by kiyote33** [comment]
Thanks Josh. I hadn't spotted that it was there already...

**Comment by joshreisner** [comment]
It's there but currently only works for CSV imports. reopening

**Comment by kiyote33** [comment]
Ugh.  I closed without thinking that through. You beat me to reopening.  Again thx...
