### ISSUE TITLE
Support for Online Meetings

### ISSUE THREAD

**Issue by nutjob4life** [code4recovery/12-step-meeting-list#62]
Hi folks! Over in [Recovery Dharma](https://recoverydharma.org/) we use 12 Step Meeting List for all of our meetings, whether in-person in the United States or around the world—as well as for online meetings.

However, for *online meetings* we've got a few challenges:

- We have to use a special `*Online` region  to get them to appear separately.
- Arbitrarily we set the address to just "United States" because *we have to put in something*.
- That puts a map on each meeting page smack dab in the middle of the US that is meaningless (and worse, takes up the majority of each online meeting page).
- We end up overloading the title field with international time info because there's no way to indicate time zones.

I realize this is a big ask, but as a first cut, simply providing a checkbox for online meetings or some way to disable the map would be enormously helpful (people from London don't need driving directions to Dearing, Kansas). What do you think? Time zone issues present a host of problems but they can be addressed later.

**Comment by joshreisner** [comment]
Hey there. I think we worked together a few years ago setting up the old Refuge Recovery site.

I've gotten this request many times over the years, and believe this plugin is not the right format for entering meetings that are online and/or don't have a location. Simply use a different page for those on your site so that they can be in a separate list, or develop a new plugin.

I'm working on a new project for AA-Intergroup.org (https://github.com/code4recovery/oiaa) that is trying to rethink what such a meeting finder would look like if it didn't have a map and addresses in it, and was time-zone agnostic. 

You'd be welcome to borrow any of that code. It uses a Google Sheet as the data source but could easily be adapted to WP, esp with a tool like Advanced Custom Fields.

But I'd advise not trying to use 12 Step Meeting List to that purpose.
