### ISSUE TITLE
Optional Admin Settings to trigger 'No District Selected'  and 'No Group Name' warnings

### ISSUE THREAD

**Issue by kiyote33** [code4recovery/12-step-meeting-list#711]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/709

<div type='discussions-op-text'>

<sup>Originally posted by **Grateful-Viv** February 28, 2022</sup>
TMSL v3.13 added a fix to the dropdown list.  See #586 which brought up the issue of when someone added or edited a meeting and selected group it defaulted to the word "District" if one wasn't selected from the dropdown list. 

But now if I don't select a district from the dropdown, it defaults to "None" and displays it as blank. 

Shouldn't the admin have to select one of the districts from the dropdown? Can a meeting says it's a group but not belong to a district? I'm not so sure that's the way it works, but TSML v3.13 allows that to happen.

What it doesn't allow is to select **Part of a group**, but not enter a group name. In that case radio button switches from **Part of a group** to **Individual meeting** when I try to save it. And that is the way it should be. But why isn't that the case also for defaulting to None for District from the dropdown list?

I would like to suggest an error flag come up when someone tries to save a meeting entry that doesn't select from the District dropdown to alert them they must, or revert back to Individual Meeting. And perhaps also add flag when someone tries to save a meeting entry that doesn't have a group name entered even though they selected **Part of a group**. Right now, it just reverts back to Individual Meeting without any explanation.</div>

**Comment by joshreisner** [comment]
i think we need to discuss this more before considering it actionable. i see lots of reasons not to have this functionality

**Comment by brianw-area24** [comment]
See also #334, they may be related

**Comment by joshreisner** [comment]
i think brian is right about these tickets being related. according to my reading of this i think that #1043 which fixes #334 will solve the main problem this ticket is getting at:

if i have a group that has a district, then go to add a new meeting and select that group, the district dropdown would not be auto-selected for me, even though the rest of the group info is populated (bad). if i then failed to select the district manually, i would be in danger of removing the group from the district (even worse). #1043 should fix it.

however i don't think that we should _always_ warn a user if a district is not selected, because as Wayne notes in the discussion, groups don't by definition have to belong to districts, and we have other programs also to think about. therefore i am going to close this ticket and recommend that we move forward just by fixing #334 with #1043

i dont think it's a big deal if a user selects "part of a group" but fails to enter a group name and hits save and sees that it's reverted to "individual meeting" 

by all means please reopen if i'm being too hasty - definitely open to having more discussion
