### ISSUE TITLE
HTML and rich text editor in notes

### ISSUE THREAD

**Issue by liberatus1** [code4recovery/12-step-meeting-list#72]
With some meetings moving online in varied formats, it may be the most flexible approach to allow HTML input in the notes field along with a rich text editor.

Even prior to this I have several times wanted some html formatting in the notes however it would be very useful at this time.

This will make it easy to post links to online meetings along with codes and whatever else may be required.

**Comment by joshreisner** [comment]
This doesn't really impact the core of the request but as an FYI, HTML can't be displayed in the Meeting Guide app because it's a security risk for users. In React they call the technique `dangerouslySetInnerHTML` for a reason :)

The only way to get tappable Zoom links into the app would be by adding new fields, and it sounds like the way to do that would be to create a companion plugin.

**Comment by liberatus1** [comment]
Hey Josh, yeah sorry I didn't follow this up quickly I realised that soon after posting it would pull the HTML into the app as well. Then I saw you guys may be working on some functionality to add a field(s) for online meetings, plus I just worked around it on the front end as you've already seen in the tiaa forum and it's working fine, so I'll close this issue.

Thank you for your awesome service!!!
