### ISSUE TITLE
Allow non-numeric characters (comma and poundsign) in online meeting phone number TEL: LINK 

### ISSUE THREAD

**Issue by alex-m-dc** [code4recovery/12-step-meeting-list#86]
Currently, the meeting/group phone number allows a phone number like this to be dialed through the link: (646) 558-8656,,820445398#    note the commas which each provide 2 seconds of pause from the connection time to when the second set of numbers is dialed and the pound sign which completes the connection to the online meeting.

https://www.howtogeek.com/263546/how-to-dial-phone-extensions-automatically-with-your-iphone/ 

Note this example on our website with the phone number working properly in the group information, but not properly in the  online meeting link. https://aa-dc.org/meetings/epiphanies-5

BTW - AKA "One touch mobile" link. https://support.pragmatic-conferencing.com/hc/en-us/articles/115010580808-One-Touch-Dialing-from-your-mobile

Thanks!

Available for questions: Alex M, 267-231-2174

**Comment by tech2serve** [comment]
I'm going to have to go and tweak my system. When I hit a phone call link on it, it automatically brings up Zoom, which I think is not what your issue is?

Can you elaborate on what is not working? Does clicking on the phone number not call into the meeting?

And can you confirm we're only talking about the two links in this section?

<img width="300" alt="image" src="https://user-images.githubusercontent.com/31904316/77928543-2a4ed580-726e-11ea-898a-27eb6063a03a.png">

**Comment by tech2serve** [comment]
Hey Alex--

I think I have it figured out. Zoom will still prompt for a participant ID.

Assuming this passes our testing, this fix will come out with the next release.
