### ISSUE TITLE
List meetings by group instead of location

### ISSUE THREAD

**Issue by kiyote33** [code4recovery/12-step-meeting-list#891]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/876

<div type='discussions-op-text'>

<sup>Originally posted by **dallasintergroup** July 18, 2022</sup>
Hi, thanks for this great plugin! It has been a HUGE help!

Several of our site users have expressed frustration at not being able to create a link which quickly pulls up a list of all meetings held by a group. The only option close to this currently, is to click on "...other meetings at this location" which isn't always helpful, since a location can host multiple groups. Additionally, some meetings of a group may be online, making the location different, so these meetings wouldn't appear on the location list. 

The only way I've found around this is to search for the desired meeting, switch results to "any day" and then copy the link for that search query. A clean and simple list of all meetings which are part of the same group would be a great benefit (was this not a feature before...I vaguely recall...?)

Thank you for your time and effort. 
Sam</div>

**Comment by kiyote33** [comment]
One suggestion is to add a "...other meetings supported by this group" link below the "...other meetings at this location" link.

**Comment by tim-rohrer** [comment]
I believe being able to filter by a group is a great idea. 

As discussed, this issue should probably transferred to TSML-UI since that is the front-end we're planning to focus upon. @code4recovery/tsml-maintainers, @code4recovery/tsml-explorers  ok with transferring to TSML-UI?

I suggest we discuss pros/cons in more detail during our meeting 8/13, and vote. Or, people state their thoughts here on GitHub..

**Comment by joshreisner** [comment]
i think it would be misplaced to switch this to TSML UI because this is a report about TSML, and the interfaces are pretty different in this regard. please advise them to switch their interface to TSML UI and see if that helps. if they have a request pertaining to TSML UI then by all means post an issue there.

TSML has a search autocomplete dropdown that shows groups in in it, but when you click a group it doesn't seem to work properly. here's a screenshot from trying to search for "Carrollton Group" on https://www.aadallas.org/wordpress/meetings/?tsml-day=6&tsml-query=carrollton%20group

<img width="1210" alt="Screen Shot 2022-07-30 at 4 35 08 PM" src="https://user-images.githubusercontent.com/1551689/182003554-ba135f14-bc29-4894-b0ee-a072fb6a65f6.png">

It doesn't search with an exact match, so it doesn't seem possible to isolate Carrollton Group meetings from other meetings in Carrollton, TX. (Also it is console.logging group information that includes possibly-private contact information, fyi)

Meanwhile TSML UI doesn't have that dropdown, it live-searches the list. Searching "Carrollton Group" in TSML UI will provide an exact match.

Also, TSML UI shows all other location and group meetings (in two separate lists) in the detail screen of each meeting, rather than having a location landing page like TSML does.

For these reasons I don't think that this issue would really apply to TSML UI.

**Comment by tim-rohrer** [comment]
> Also, TSML UI shows all other location and group meetings (in two separate lists) in the detail screen of each meeting, rather than having a location landing page like TSML does.
> 

I believe this is the real ask being made by Dallas, or some variant thereof. I agree, they should be shown TSML-UI’s approach to see if it suffices.

Discussed during our meeting today, the team isn’t interested in modifying TSML’s public side to support this since the plan is to migrate to TSML-UI as *the* interface. So the discussion/issue (if it still is one after Dallas is consulted) is about TSML-UI.

**Comment by joshreisner** [comment]
sounds good. sounds like we can close this as `wontfix` then.

tell them the thing about the quote-searching though! very helpful when searching for a specific group name

**Comment by kiyote33** [comment]
Hi Tim,

 

I seem to have missed something here. My understanding was that Mark, Brian, & I thought this would be a simple feature enhancement to TSML. I don’t recall any discussion about transferring this item to TSML-UI. 

 

Mark & Brian, could you two chime in here?

 

Wayne

**Comment by joshreisner** [comment]
this has been open for a while. i'm going to close it, but please reopen if it's a feature you still want to add to TSML
